version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "websockets"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
