/**
 * Sample API Sync Wrapper for Shopify Webhooks
 * This demonstrates how incoming webhooks (e.g., orders/create or inventory_levels/update)
 * sync with the local Inventory Vault and CRM.
 */

class ShopifySyncWrapper {
    constructor(localDb) {
      this.db = localDb; // Mock local database instance containing Customers, Products, and Inventory_Logs
    }
  
    /**
     * Handle incoming Shopify Webhook for Order Creation
     * @param {Object} shopifyOrderPayload - The payload received from Shopify webhook
     */
    async handleOrderCreated(shopifyOrderPayload) {
      console.log(`[SYNC] Processing new order from Shopify: ${shopifyOrderPayload.id}`);
  
      const { customer, line_items, total_price } = shopifyOrderPayload;
  
      // 1. Sync Customer Data
      let localCustomer = null;
      if (customer) {
        // Try to find by the GraphQL compatible ID
        localCustomer = await this.db.customers.findById(`gid://shopify/Customer/${customer.id}`);
        
        if (!localCustomer) {
          console.log(`[SYNC] Customer not found locally. Creating new profile for: ${customer.email}`);
          localCustomer = await this.db.customers.create({
            customer_id: `gid://shopify/Customer/${customer.id}`, // Compatible with Shopify GraphQL
            first_name: customer.first_name,
            last_name: customer.last_name,
            email: customer.email,
            phone: customer.phone || "",
            social_handles: {},
            personal_notes: "Auto-synced from Shopify Order",
            loyalty_points: 0,
            purchase_history: [],
            shopify_sync_status: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          });
        }
  
        // 2. Update Loyalty Points ($1 = 1 point)
        const pointsEarned = Math.floor(parseFloat(total_price));
        await this.db.customers.addPoints(localCustomer.customer_id, pointsEarned);
        console.log(`[SYNC] Added ${pointsEarned} loyalty points to customer ${localCustomer.customer_id}`);
      }
  
      // 3. Sync Inventory & Create Log
      for (const item of line_items) {
        // Find local product by SKU
        const product = await this.db.products.findBySku(item.sku);
        if (product) {
          // Decrement local stock since it was sold on Shopify
          await this.db.products.decrementStock(product.product_id, item.quantity);
          console.log(`[SYNC] Decremented stock for SKU: ${item.sku} by ${item.quantity}`);
          
          // Log transaction (Stock Out)
          await this.db.inventory_logs.create({
            transaction_id: `shopify_${shopifyOrderPayload.id}_${item.id}`,
            product_id: product.product_id,
            customer_id: localCustomer ? localCustomer.customer_id : "GUEST",
            transaction_type: 'OUT',
            quantity: item.quantity,
            price_at_sale: parseFloat(item.price),
            source: 'SHOPIFY_SYNC',
            timestamp: new Date().toISOString()
          });
        } else {
          console.warn(`[SYNC WARNING] SKU ${item.sku} not found in local Inventory Vault.`);
        }
      }
  
      console.log(`[SYNC] Order ${shopifyOrderPayload.id} successfully synced to Inventory Vault.`);
    }
  
    /**
     * Push local POS sale to Shopify (for unified inventory & customer tracking)
     * @param {Object} posTransaction - The local transaction object generated by QuickPOS
     */
    async pushLocalSaleToShopify(posTransaction) {
      console.log(`[SYNC] Pushing local POS transaction ${posTransaction.transaction_id} to Shopify`);
      
      try {
        // Here we would typically construct a GraphQL mutation to adjust inventory
        // using the `inventoryAdjustQuantity` mutation, and update the customer via `customerUpdate`.
        
        // Pseudo-code for the API call:
        /*
        const mutation = `
          mutation inventoryAdjustQuantity($input: InventoryAdjustQuantityInput!) {
            inventoryAdjustQuantity(input: $input) {
              inventoryLevel {
                id
                available
              }
              userErrors {
                field
                message
              }
            }
          }
        `;
        */
  
        // Simulate network delay
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Mark the local transaction & customer as synced
        posTransaction.shopify_sync_status = true;
        await this.db.inventory_logs.update(posTransaction.transaction_id, { shopify_sync_status: true });
  
        if (posTransaction.customer_id && posTransaction.customer_id !== "GUEST") {
           await this.db.customers.update(posTransaction.customer_id, { shopify_sync_status: true });
        }
  
        console.log(`[SYNC] Successfully pushed transaction ${posTransaction.transaction_id} to Shopify.`);
      } catch (error) {
        console.error("[SYNC ERROR] Failed to push local sale to Shopify", error);
      }
    }
  }
  
  export default ShopifySyncWrapper;