"""
core/tools.py

Tool definitions and execution logic for River Song AI.
Enables LLMs to perform real-world actions via function calling.
"""

from __future__ import annotations

import logging
import sqlite3
import os
import asyncio
from datetime import datetime, timezone
from typing import Any, Dict

from config.settings import get_settings

logger = logging.getLogger(__name__)

# TOOL_SCHEMAS (and its Playwright extension) live in core/tools_schemas.py;
# re-exported here so existing `from core.tools import TOOL_SCHEMAS` works.
from core.tools_schemas import TOOL_SCHEMAS  # noqa: E402,F401


# =============================================================================
# Tool Executor
# =============================================================================


async def execute_tool(
        tool_name: str, tool_input: Dict[str, Any], context: Dict[str, Any]) -> str:
    """
    Dispatches a tool call to the appropriate internal provider or database.

    Args:
        tool_name:  The name of the tool chosen by the LLM.
        tool_input: The arguments generated by the LLM.
        context:    Contains metadata like user_id and database connection info.

    Returns:
        A short plain-English success/failure message to be relayed to the user.
    """
    user_id = context.get("user_id", "primary_user")
    logger.info(
        "Executing tool '%s' for user '%s' with input: %s",
        tool_name,
        user_id,
        tool_input)

    try:
        if tool_name == "remember_fact":
            return await _exec_remember_fact(tool_input, context)
        elif tool_name == "forget_memory":
            return await _exec_forget_memory(tool_input, context)
        elif tool_name == "recall_memory":
            return await _exec_recall_memory(tool_input, context)
        elif tool_name == "update_memory":
            return await _exec_update_memory(tool_input, context)
        elif tool_name == "take_note":
            return await _exec_take_note(tool_input, context)
        elif tool_name == "append_note":
            return await _exec_append_note(tool_input, context)
        elif tool_name == "journal":
            return await _exec_journal(tool_input, context)
        elif tool_name == "find_notes":
            return await _exec_find_notes(tool_input, context)
        elif tool_name == "read_note":
            return await _exec_read_note(tool_input, context)
        elif tool_name == "deep_research":
            return await _exec_deep_research(tool_input, user_id)

        elif tool_name == "create_calendar_event":
            return await _exec_calendar_event(tool_input, user_id)

        elif tool_name == "add_asset":
            return await _exec_add_asset(tool_input, user_id)
        elif tool_name == "find_asset":
            return await _exec_find_asset(tool_input, user_id)
        elif tool_name == "asset_summary":
            return await _exec_asset_summary(tool_input, user_id)
        elif tool_name == "registry_health":
            return await _exec_registry_health(tool_input, user_id)
        elif tool_name == "warranty_check":
            return await _exec_warranty_check(tool_input, user_id)

        elif tool_name == "add_shopping_list_item":
            return await _exec_add_shopping_list(tool_input, user_id)

        elif tool_name == "set_reminder":
            return await _exec_set_reminder(tool_input, user_id)
            
        elif tool_name == "set_timer":
            return await _exec_set_timer(tool_input, user_id)

        elif tool_name == "control_device":
            return await _exec_control_device(tool_input, user_id)

        elif tool_name == "alias_device":
            return await _exec_alias_device(tool_input, user_id)

        elif tool_name == "log_vehicle_maintenance":
            # type: ignore
            return await _exec_vehicle_maintenance(tool_input, context)  # type: ignore

        elif tool_name == "get_vehicle_status": return await _exec_get_vehicle_status(tool_input, user_id)
        elif tool_name == "get_vehicle_spec": return await _exec_get_vehicle_spec(tool_input, user_id)
        elif tool_name == "query_vehicle_manual": return await _exec_query_vehicle_manual(tool_input, user_id)
        elif tool_name == "record_odometer": return await _exec_record_odometer(tool_input, user_id)
        elif tool_name == "find_parts": return await _exec_find_parts(tool_input, user_id)
        elif tool_name == "list_vehicles":
            return await _exec_list_vehicles(tool_input, context)
            
        elif tool_name == "get_vehicle_status":
            return await _exec_get_vehicle_status(tool_input, context)
            
        elif tool_name == "get_vehicle_spec":
            return await _exec_get_vehicle_spec(tool_input, context)
            
        elif tool_name == "query_vehicle_manual":
            return await _exec_query_vehicle_manual(tool_input, context)
            
        elif tool_name == "record_odometer":
            return await _exec_record_odometer(tool_input, context)

        elif tool_name == "add_recipe_to_library":
            return await _exec_add_recipe(tool_input, user_id)

        elif tool_name == "create_routine":
            return await _exec_create_routine(tool_input, user_id)
        elif tool_name == "list_routines":
            return await _exec_list_routines(user_id)
        elif tool_name == "update_routine":
            return await _exec_update_routine(tool_input, user_id)
        elif tool_name == "delete_routine":
            return await _exec_delete_routine(tool_input, user_id)
        elif tool_name == "run_routine_now":
            return await _exec_run_routine_now(tool_input, user_id)

        elif tool_name == "check_reading_status":
            return await _exec_check_reading_status(tool_input, user_id)

        elif tool_name == "sync_kindle_library":
            return await _exec_sync_kindle(tool_input, user_id)

        elif tool_name == "search_commerce_products":
            return await _exec_search_commerce_products(tool_input, user_id)

        elif tool_name == "create_commerce_sale":
            return await _exec_create_commerce_sale(tool_input, user_id)

        elif tool_name == "trigger_n8n_workflow":
            return await _exec_trigger_n8n(tool_input, user_id)

        elif tool_name == "generate_business_report":
            return await _exec_generate_business_report(tool_input, user_id)

        elif tool_name == "web_search":
            return await _exec_web_search(tool_input, user_id)

        elif tool_name == "search_emails":
            return await _exec_search_emails(tool_input, user_id)

        elif tool_name == "get_weather":
            return await _exec_get_weather(tool_input, user_id)

        elif tool_name == "generate_image":
            return await _exec_generate_image(tool_input, user_id)

        elif tool_name == "search_google_books":
            return await _exec_search_google_books(tool_input, user_id)

        elif tool_name == "add_google_task":
            return await _exec_add_google_task(tool_input, user_id)

        elif tool_name == "list_google_tasks":
            return await _exec_list_google_tasks(tool_input, user_id)

        elif tool_name == "save_vault_note":
            return await _exec_save_vault_note(tool_input, user_id)

        elif tool_name == "read_vault_note":
            return await _exec_read_vault_note(tool_input, user_id)

        elif tool_name == "search_vault":
            return await _exec_search_vault(tool_input, user_id)

        elif tool_name == "code_interpreter":
            return await _exec_code_interpreter(tool_input, user_id)

        elif tool_name in ("browser_navigate", "browser_extract_text",
                           "browser_click", "browser_screenshot",
                           "browser_vision_on_page"):
            # Q3#13 — Playwright browser tools. Flag-gated; the provider
            # short-circuits when disabled.
            from providers.web.playwright_browser import PLAYWRIGHT_TOOL_DISPATCH
            fn = PLAYWRIGHT_TOOL_DISPATCH.get(tool_name)
            if fn is None:
                return f"Unknown browser tool: {tool_name}"
            return await fn(tool_input or {})

        elif tool_name == "mow_command":
            return await _exec_mow_command(tool_input, user_id)

        else:
            return f"Unknown tool '{tool_name}' requested."

    except Exception as exc:
        logger.error(
            "Unexpected error executing tool '%s': %s",
            tool_name,
            exc)
        return f"Tool execution failed due to an internal error: {exc}"


async def _exec_deep_research(args: dict, user_id: str) -> str:
    try:
        query = args.get("query", "").strip()
        if not query:
            return "Please provide a query for deep research."
            
        from core.deep_research import decompose_query, run_deep_research
        from config.settings import get_settings
        
        if not getattr(get_settings(), "deep_research_enabled", False):
            return "Deep Research is disabled in settings."
            
        # Try to estimate complexity
        sub_queries = await decompose_query(query, count=2)
        count = len(sub_queries)
        
        # Quick: run inside the turn. Big: enqueue background job.
        
        def _get_store():
            try:
                from main import get_app
                app = get_app()
                if app:
                    return app.state.memory_manager._store
            except Exception:
                pass
            return None
            
        store = _get_store()
        if not store:
            return "Cannot run research without document store."
            
        if count <= 2:
            # Inline execution
            try:
                result = await run_deep_research(query, user_id=user_id, store=store)
                report = result.get("report", "")
                doc_id = result.get("document_id")
                return f"I've completed the deep research. The report is saved to your Documents (ID: {doc_id}).\n\n{report}"
            except Exception as e:
                logger.error(f"Inline deep research failed: {e}")
                return f"Deep research encountered an error: {e}"

        # Big: background execution
        import asyncio
        
        async def background_research():
            try:
                result = await run_deep_research(query, user_id=user_id, store=store)
                logger.info(f"Background research complete for '{query}': doc_id={result.get('document_id')}")
                
                # Append to the session
                session_id = args.get("session_id") or context.get("session_id")
                if session_id:
                    report = result.get("report", "Research complete.")
                    doc_id = result.get("document_id")
                    
                    content = f"I've finished the deep research on '{query}'.\n\n"
                    if doc_id:
                        content += f"I've saved the full report to your Documents.\n\n"
                    content += report
                        
                    await store.save_chat_message(
                        user_id=user_id,
                        session_id=session_id,
                        role="assistant",
                        content=content
                    )
                    
                    # Try to push via FCM
                    try:
                        from providers.notifier.fcm_notifier import FCMNotifier
                        await FCMNotifier(store).send_notification(
                            user_id=user_id,
                            title="Research Complete",
                            body=f"Your deep research on '{query}' is ready.",
                            data={"session_id": session_id, "doc_id": doc_id or ""}
                        )
                    except Exception as e:
                        logger.debug("Failed to push FCM notification for research: %s", e)
                        
            except Exception as e:
                logger.error(f"Background research failed: {e}")
                
        asyncio.create_task(background_research())
        return f"I'm starting a deep dive on '{query}'. I'll let you know when the report is ready. It will be saved to your documents."
        
    except Exception as exc:
        logger.error("deep_research failed: %s", exc)
        return f"Deep research failed: {exc}"


# -----------------------------------------------------------------------------
# Individual Executors (Private)
# -----------------------------------------------------------------------------

async def _exec_calendar_event(args: dict, user_id: str) -> str:
    try:
        from providers.google.calendar import build_calendar_provider
        from datetime import datetime

        provider = build_calendar_provider(user_id=user_id)

        # Parse date and time
        date_obj = datetime.strptime(args["date"], "%Y-%m-%d").date()
        time_obj = datetime.strptime(args["time"], "%H:%M").time()
        start_dt = datetime.combine(date_obj, time_obj)

        await provider.create_event(
            summary=args["title"],
            start_dt=start_dt,
            end_dt=None,  # Provider defaults to +1 hour, which is fine
        )
        return f"Successfully scheduled '{args['title']}' for {args['date']} at {args['time']} on your Google Calendar."
    except Exception as exc:
        logger.error("Calendar tool failed: %s", exc)
        return f"I tried to create the calendar event for '{args['title']}', but encountered an issue: {str(exc)}. Make sure Google is linked in Settings."


async def _exec_add_asset(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.management import create_item, get_or_create_inv_user, get_homes_for_user, create_home, ItemCategory
        from inventory.models import InvHome
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            homes = get_homes_for_user(db, str(inv_user.id))
            
            home = None
            if args.get('home'):
                home = next((h for h in homes if h.name.lower() == args['home'].lower()), None)
            
            if not home:
                if not homes:
                    home = create_home(db, str(inv_user.id), "Primary Residence", "")
                else:
                    home = homes[0]
            
            cat_str = args.get('category', 'OTHER').upper()
            try:
                cat = ItemCategory(cat_str)
            except ValueError:
                cat = ItemCategory.OTHER
                
            item = create_item(db, str(inv_user.id), str(home.id), {
                "name": args['name'],
                "location": args.get('location'),
                "category": cat,
                "description": args.get('details', '')
            })
            return f"Added {item.name} to the inventory at {item.location} in {home.name}."
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_find_asset(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            
            query_str = args.get('query', '').lower()
            
            items = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id).all()
            matches = []
            for item in items:
                if (query_str in item.name.lower() or 
                    (item.ein and query_str in item.ein.lower()) or 
                    (item.serial_number and query_str in item.serial_number.lower())):
                    matches.append(item)
                    
            if not matches:
                return f"No assets found matching '{query_str}'."
            
            lines = [f"Found {len(matches)} matching asset(s):"]
            for m in matches:
                audit_info = f"Last seen: {m.last_audit_date.date()}" if m.last_audit_date else "Never audited"
                home_name = m.home.name if m.home else "Unknown Home"
                lines.append(f"- {m.name} (Location: {m.location} in {home_name}). {audit_info}.")
            return "\\n".join(lines)
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_asset_summary(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        from decimal import Decimal
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            scope = args.get('scope', '').lower()
            
            items = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id).all()
            
            if scope and 'home' not in scope and 'room' not in scope and 'categor' not in scope:
                items = [i for i in items if scope in i.name.lower() or (i.category and scope in i.category.value.lower()) or (i.location and scope in i.location.lower()) or (i.home and scope in i.home.name.lower())]
                
            total_count = len(items)
            total_value = sum((i.replacement_cost or i.purchase_price or Decimal('0.0')) for i in items)
            
            return f"Asset Summary: You have {total_count} items matching your criteria, with a total estimated replacement value of ${total_value:,.2f}."
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_registry_health(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            home_filter = args.get('home')
            
            query = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id)
            if home_filter:
                query = query.filter(InvHome.name.ilike(f"%{home_filter}%"))
                
            items = query.all()
            missing_photos = sum(1 for i in items if not i.attachments)
            missing_serials = sum(1 for i in items if not i.serial_number)
            missing_values = sum(1 for i in items if not i.replacement_cost and not i.purchase_price)
            missing_receipts = sum(1 for i in items if not i.receipt_image_path)
            
            return (f"Registry Health Report (Total Items: {len(items)}):\\n"
                    f"- Missing Photos: {missing_photos}\\n"
                    f"- Missing Serial Numbers: {missing_serials}\\n"
                    f"- Missing Values: {missing_values}\\n"
                    f"- Missing Receipts: {missing_receipts}\\n"
                    f"Please update your stash for better claims readiness.")
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_warranty_check(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        from datetime import date, timedelta
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            item_name = args.get('item_name')
            days = args.get('expiring_within_days', 30)
            
            query = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id)
            if item_name:
                query = query.filter(InventoryItem.name.ilike(f"%{item_name}%"))
                
            items = query.all()
            today = date.today()
            cutoff = today + timedelta(days=days)
            
            if item_name and len(items) == 1:
                item = items[0]
                if not item.warranty_expiry_date:
                    return f"The {item.name} does not have a warranty expiration date recorded."
                status = "expired" if item.warranty_expiry_date < today else "valid"
                return f"The warranty for {item.name} is {status} (expires/expired on {item.warranty_expiry_date.isoformat()})."
                
            expiring_soon = [i for i in items if i.warranty_expiry_date and today <= i.warranty_expiry_date <= cutoff]
            expired = [i for i in items if i.warranty_expiry_date and i.warranty_expiry_date < today]
            
            lines = [f"Warranty Check (Looking ahead {days} days):"]
            lines.append(f"Expiring Soon ({len(expiring_soon)}): " + ", ".join(f"{i.name} ({i.warranty_expiry_date})" for i in expiring_soon) if expiring_soon else "Expiring Soon: None")
            lines.append(f"Already Expired ({len(expired)}): " + ", ".join(f"{i.name}" for i in expired) if expired else "Already Expired: None")
            return "\\n".join(lines)
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_add_shopping_list(args: dict, user_id: str) -> str:
    from db.database import SessionLocal
    from culinary.models import Household, ShoppingListItem, ListSource
    item = args.get("item")
    qty = args.get("quantity")

    if not item:
        return "Error: item is required."

    def _sync_work():
        db = SessionLocal()
        try:
            hh = db.query(Household).filter(Household.owner_id == user_id).first()
            if not hh:
                return "Error: Household not found."
            sl_item = ShoppingListItem(
                household_id=hh.id,
                name=item,
                qty=str(qty) if qty else None,
                category="grocery",
                source=ListSource.CHAT,
                added_by=user_id
            )
            db.add(sl_item)
            db.commit()
            return f"Added '{item}' to your shopping list."
        finally:
            db.close()

    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_set_reminder(args: dict, user_id: str) -> str:
    settings = get_settings()
    db_path = settings.db_path

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS reminders (
                    id INTEGER PRIMARY KEY,
                    user_id TEXT,
                    message TEXT,
                    remind_at TEXT,
                    created_at TEXT
                )
            """)
            conn.execute(
                """INSERT INTO reminders (user_id, message, remind_at, created_at) VALUES (?, ?, ?, ?)""",
                (user_id, args['message'], args['datetime_str'],
                 datetime.now(timezone.utc).isoformat())
            )
            conn.commit()
            return f"Reminder set: '{args['message']}' for {args['datetime_str']}."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_control_device(args: dict, user_id: str) -> str:
    try:
        from providers.smart_home.home_assistant import build_ha_client
        from providers.smart_home.device_registry import get_device_registry

        registry = get_device_registry()
        resolved = await registry.resolve(args['device_name'])
        if not resolved:
            return f"I couldn't find a device named '{args['device_name']}' in your registry."

        async with build_ha_client() as client:
            if isinstance(resolved, list):
                await client.execute_action_on_many(resolved, args['action'], args.get('value'))
            else:
                await client.execute_action(resolved, args['action'], args.get('value'))

        return f"Confirmed. Turned {args['action']} the {args['device_name']}."
    except Exception:
        return f"Home Assistant isn't reachable right now — I couldn't turn {args['action']} the {args['device_name']}."


async def _exec_alias_device(args: dict, user_id: str) -> str:
    """
    Updates the ha_entities table to add a new alias to an entity.
    """
    from core.family import is_feature_enabled_for
    if not await is_feature_enabled_for(user_id, "home"):
        return "Home automation features are disabled for your account."

    entity_id = args.get("entity_id")
    alias = args.get("alias")
    if not entity_id or not alias:
        return "Both entity_id and alias must be provided."

    from main import get_app
    app = get_app()
    if not app:
        return "Internal error: app context not found."
    
    store = app.state.memory_manager._store
    try:
        import json
        rows = await store._fetch_all("SELECT aliases FROM ha_entities WHERE entity_id = ?", (entity_id,))
        if not rows:
            return f"Entity {entity_id} not found in the registry."
            
        current_aliases = json.loads(rows[0]["aliases"])
        if alias not in current_aliases:
            current_aliases.append(alias)
            await store._execute(
                "UPDATE ha_entities SET aliases = ? WHERE entity_id = ?",
                (json.dumps(current_aliases), entity_id)
            )
            return f"Successfully learned the name '{alias}' for {entity_id}."
        return f"I already know '{alias}' as a name for {entity_id}."
    except Exception as e:
        logger.error("Error aliasing device: %s", e)
        return "Failed to save the new name."


async def _exec_vehicle_maintenance(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    
    vehicle_id = context.get("vehicle_id")
    if not vehicle_id:
        vehicle_id = await _resolve_vehicle(args.get("vehicle", ""), user_id)
    if not vehicle_id:
        return "No vehicle_id in context and could not resolve vehicle."


    def _sync_work():
        from vehicles.management import get_vehicles, create_service_log
        import difflib
        from datetime import datetime, timezone

        db = context.get("db")
        if not db:
            from sqlalchemy import create_engine
            from sqlalchemy.orm import sessionmaker
            engine = create_engine(
                os.environ.get(
                    "VEHICLES_DB_URL",
                    "sqlite:///./data/vehicles.db"))
            db = sessionmaker(bind=engine)()
            close_db = True
        else:
            close_db = False

        try:
            # If vehicle_id is missing, try to resolve from args
            if not vehicle_id:
                vehicle_name = args.get('vehicle_name')
                if not vehicle_name:
                    return {"error": "Must specify a vehicle_name if not already in context."}
                
                v = _resolve_vehicle_sync(db, user_id, vehicle_name)
                if not v:
                    return {"error": f"Could not find a vehicle matching '{vehicle_name}'."}
                vehicle_id = str(v.id)
            else:
                vehicles = get_vehicles(db, user_id)  # type: ignore
                v = next((v for v in vehicles if str(v.id) == vehicle_id), None)
                if not v:
                    return {"error": "Vehicle not found."}

            service_type = args.get('service_type', '')
            date_str = args.get('date', datetime.now(timezone.utc).date().isoformat())
            mileage = args.get('mileage')
            cost = args.get('cost')
            notes = args.get('notes', '')

            try:
                service_date = datetime.strptime(date_str, "%Y-%m-%d")
            except ValueError:
                service_date = datetime.now(timezone.utc)

            # Fuzzy match the checkpoint
            checkpoints = {cp.description: cp for cp in v.check_points}
            descriptions = list(checkpoints.keys())

            matches = difflib.get_close_matches(service_type, descriptions, n=1, cutoff=0.6)
            matched_cp = None
            if matches:
                matched_cp = checkpoints[matches[0]]

            check_results = []
            if matched_cp:
                check_results.append({
                    "description": matched_cp.description,
                    "check_point_id": str(matched_cp.id),
                    "status": "pass",
                    "passed": True
                })
                # Update checkpoint explicitly
                if mileage is not None:
                    matched_cp.last_service_odometer = mileage
                matched_cp.last_service_date = service_date
                db.commit()

            log = create_service_log(
                db, user_id, vehicle_id,  # type: ignore
                service_date=service_date,
                odometer=mileage,
                service_type=service_type,
                cost=cost,
                notes=notes,
                check_results=check_results
            )
            
            # Record usage reading if mileage provided
            if mileage is not None:
                from vehicles.models import UsageReading, UsageUnit, UsageSource
                ur = UsageReading(
                    vehicle_id=v.id,
                    value=mileage,
                    unit=UsageUnit.MILES,
                    source=UsageSource.SERVICE_LOG,
                    recorded_at=service_date
                )
                db.add(ur)
                db.commit()

            result = {
                "success": True,
                "message": f"Logged '{matched_cp.description if matched_cp else service_type}' at {mileage} miles.",
                "matched_checkpoint": matched_cp.description if matched_cp else None,
                "log_id": str(log.id)
            }
            return result
        finally:
            if close_db:
                db.close()

    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


def _resolve_vehicle_sync(db, user_id, query):
    import difflib
    from api.routes.vehicles import get_vehicles
    vehicles = get_vehicles(db, user_id)
    if not vehicles:
        return None
    
    # Try exact nickname
    for v in vehicles:
        if v.nickname and v.nickname.lower() == query.lower():
            return v
    
    names = {}
    for v in vehicles:
        n1 = v.nickname or ""
        n2 = f"{v.year} {v.make} {v.model}"
        names[n1.lower()] = v
        names[n2.lower()] = v
    
    matches = difflib.get_close_matches(query.lower(), list(names.keys()), n=1, cutoff=0.4)
    if matches:
        return names[matches[0]]
    return vehicles[0] # fallback


def _get_db_for_tools(context):
    db = context.get("db")
    if not db:
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker
        engine = create_engine(os.environ.get("VEHICLES_DB_URL", "sqlite:///./data/vehicles.db"))
        return sessionmaker(bind=engine)(), True
    return db, False


async def _exec_list_vehicles(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    def _sync():
        db, close = _get_db_for_tools(context)
        try:
            from api.routes.vehicles import get_vehicles, get_maintenance_timeline
            vehicles = get_vehicles(db, user_id)
            res = []
            for v in vehicles:
                try:
                    tl = get_maintenance_timeline(str(v.id), None, None, db, user_id)
                except Exception:
                    tl = {}
                res.append({
                    "id": str(v.id),
                    "name": v.nickname or f"{v.year} {v.make} {v.model}",
                    "effective_odometer": tl.get("eff_odometer")
                })
            return {"vehicles": res}
        finally:
            if close: db.close()
    return await asyncio.get_running_loop().run_in_executor(None, _sync)


async def _exec_get_vehicle_status(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    v_id = context.get("vehicle_id")
    v_name = args.get("vehicle_name")
    
    def _sync():
        db, close = _get_db_for_tools(context)
        try:
            from api.routes.vehicles import get_maintenance_timeline
            vehicle_id = v_id
            if not vehicle_id and v_name:
                v = _resolve_vehicle_sync(db, user_id, v_name)
                if not v: return {"error": "Vehicle not found."}
                vehicle_id = str(v.id)
            
            if not vehicle_id:
                return {"error": "Could not determine vehicle."}
                
            tl = get_maintenance_timeline(vehicle_id, None, None, db, user_id)
            return tl
        finally:
            if close: db.close()
    return await asyncio.get_running_loop().run_in_executor(None, _sync)


async def _exec_get_vehicle_spec(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    v_id = context.get("vehicle_id")
    v_name = args.get("vehicle_name")
    item = args.get("item", "")
    
    def _sync():
        import difflib
        db, close = _get_db_for_tools(context)
        try:
            vehicle_id = v_id
            if not vehicle_id and v_name:
                v = _resolve_vehicle_sync(db, user_id, v_name)
                if not v: return {"error": "Vehicle not found."}
                vehicle_id = str(v.id)
            else:
                from api.routes.vehicles import get_vehicles
                v = next((x for x in get_vehicles(db, user_id) if str(x.id) == vehicle_id), None)
                
            if not v:
                return {"error": "Could not determine vehicle."}
                
            cps = {cp.description: cp for cp in v.check_points}
            matches = difflib.get_close_matches(item, list(cps.keys()), n=1, cutoff=0.3)
            if matches:
                cp = cps[matches[0]]
                return {
                    "checkpoint": cp.description,
                    "expected_spec": cp.expected_spec,
                    "volume": cp.volume,
                    "unit": cp.unit,
                    "torque": f"{cp.ft_lb} ft-lb" if cp.ft_lb else None
                }
            return {"error": "Spec not found."}
        finally:
            if close: db.close()
    return await asyncio.get_running_loop().run_in_executor(None, _sync)


async def _exec_query_vehicle_manual(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    v_id = context.get("vehicle_id")
    v_name = args.get("vehicle_name")
    question = args.get("question", "")
    
    # We must run this async as it uses memory_manager / llm
    db, close = _get_db_for_tools(context)
    try:
        vehicle_id = v_id
        if not vehicle_id and v_name:
            v = await asyncio.get_running_loop().run_in_executor(None, _resolve_vehicle_sync, db, user_id, v_name)
            if not v: return {"error": "Vehicle not found."}
            vehicle_id = str(v.id)
        
        if not vehicle_id:
            return {"error": "Could not determine vehicle."}
    finally:
        if close: db.close()
        
    # Use RAG with metadata filter
    from core.memory_manager import MemoryManager
    try:
        from main import get_app
        app = get_app()
        if app:
            memory_manager = app.state.memory_manager
        else:
            return {"error": "App not ready."}
    except Exception:
        return {"error": "App not ready."}
        
    results = await memory_manager.search_rag(user_id, question, n_results=5)
    # Filter strictly to vehicle_id if possible, or just return the text
    filtered = []
    for r in results:
        meta = r.get("metadata", {})
        if meta.get("vehicle_id") == vehicle_id or meta.get("doc_type") == "vehicle_manual":
            filtered.append(r["text"])
            
    if not filtered:
        return {"answer": "No relevant manual pages found."}
        
    context_str = "\n".join(filtered)
    # Summarize with LLM
    from core.llm_service import _generate_text
    prompt = f"Answer the following question about a vehicle based on the provided manual excerpts.\n\nQuestion: {question}\n\nExcerpts:\n{context_str}"
    ans = await _generate_text([{"role": "user", "content": prompt}], user_id)
    return {"answer": ans}


async def _exec_record_odometer(args: dict, context: dict) -> dict:
    user_id = context.get("user_id")
    v_id = context.get("vehicle_id")
    v_name = args.get("vehicle_name")
    val = args.get("value")
    
    if not val:
        return {"error": "Value required."}
        
    def _sync():
        db, close = _get_db_for_tools(context)
        try:
            vehicle_id = v_id
            if not vehicle_id and v_name:
                v = _resolve_vehicle_sync(db, user_id, v_name)
                if not v: return {"error": "Vehicle not found."}
                vehicle_id = str(v.id)
            else:
                from api.routes.vehicles import get_vehicles
                v = next((x for x in get_vehicles(db, user_id) if str(x.id) == vehicle_id), None)
                
            if not v:
                return {"error": "Could not determine vehicle."}
                
            from vehicles.models import UsageReading, UsageUnit, UsageSource
            from datetime import datetime, timezone
            ur = UsageReading(
                vehicle_id=v.id,
                value=val,
                unit=UsageUnit.MILES,
                source=UsageSource.MANUAL,
                recorded_at=datetime.now(timezone.utc)
            )
            db.add(ur)
            db.commit()
            return {"success": True, "message": f"Recorded {val} miles for {v.nickname or v.model}."}
        finally:
            if close: db.close()
    return await asyncio.get_running_loop().run_in_executor(None, _sync)




async def _exec_add_recipe(args: dict, user_id: str) -> str:
    settings = get_settings()
    db_path = settings.db_path

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS recipe_stubs (
                    id INTEGER PRIMARY KEY,
                    user_id TEXT,
                    title TEXT,
                    source_url TEXT,
                    notes TEXT,
                    created_at TEXT
                )
            """)
            conn.execute(
                """INSERT INTO recipe_stubs (user_id, title, source_url, notes, created_at)
                   VALUES (?, ?, ?, ?, ?)""",
                (user_id, args['title'], args.get('source_url', ''), args.get(
                    'notes', ''), datetime.now(timezone.utc).isoformat())
            )
            conn.commit()
            return f"Added '{args['title']}' to your culinary library."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_create_routine(args: dict, user_id: str) -> str:
    import uuid
    import json
    settings = get_settings()
    db_path = settings.db_path
    
    name = args.get("name", "Untitled Routine")
    trigger = args.get("trigger", "manual")
    prompt = args.get("action_description", "")
    days = args.get("days", [])
    severity = args.get("severity", "info")
    
    # Try to parse trigger as time if it looks like HH:MM
    time_val = None
    if ":" in trigger and any(c.isdigit() for c in trigger):
        time_val = trigger.strip()
        trigger = "schedule"
        
    rid = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            conn.execute(
                """
                INSERT INTO routines
                    (id, user_id, name, trigger, time, days, prompt, type, severity, enabled, created_at, updated_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                (rid, user_id, name, trigger, time_val, json.dumps(days), prompt, "simple", severity, 1, now, now)
            )
            conn.commit()
            return f"Created routine '{name}' with ID {rid}."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_list_routines(user_id: str) -> str:
    db_path = get_settings().db_path
    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            rows = conn.execute("SELECT id, name, trigger, time, days, prompt, severity, enabled FROM routines WHERE user_id = ?", (user_id,)).fetchall()
            if not rows:
                return "You have no routines configured."
            lines = ["Here are your routines:"]
            import json
            for r in rows:
                days = json.loads(r[4])
                days_str = "every day" if not days else ", ".join(days)
                t = r[3] if r[3] else r[2]
                en = "" if r[7] else " (disabled)"
                lines.append(f"- {r[1]} (ID: {r[0]}){en}: runs at {t} on {days_str}. Action: {r[5]}")
            return "\n".join(lines)
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_update_routine(args: dict, user_id: str) -> str:
    db_path = get_settings().db_path
    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            rid = args.get("routine_id")
            if not rid:
                return "routine_id is required."
            
            allowed = {"name", "trigger", "action_description", "days", "severity"}
            set_parts, vals = [], []
            import json
            for k, v in args.items():
                if k not in allowed: continue
                db_k = k
                if k == "action_description": db_k = "prompt"
                
                if k == "days":
                    v = json.dumps(v)
                elif k == "trigger":
                    if ":" in v and any(c.isdigit() for c in v):
                        set_parts.append("time = ?")
                        vals.append(v.strip())
                        v = "schedule"
                
                set_parts.append(f"{db_k} = ?")
                vals.append(v)
            
            if not set_parts:
                return "No fields to update."
            
            set_parts.append("updated_at = ?")
            vals.append(datetime.now(timezone.utc).isoformat())
            
            vals.extend([rid, user_id])
            
            conn.execute(f"UPDATE routines SET {', '.join(set_parts)} WHERE id = ? AND user_id = ?", vals)
            conn.commit()
            return f"Routine {rid} updated."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_delete_routine(args: dict, user_id: str) -> str:
    db_path = get_settings().db_path
    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            rid = args.get("routine_id")
            conn.execute("DELETE FROM routines WHERE id = ? AND user_id = ?", (rid, user_id))
            conn.commit()
            return f"Routine {rid} deleted."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_run_routine_now(args: dict, user_id: str) -> str:
    db_path = get_settings().db_path
    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            rid = args.get("routine_id")
            row = conn.execute("SELECT name, prompt, type, severity FROM routines WHERE id = ? AND user_id = ?", (rid, user_id)).fetchone()
            if not row:
                return "Routine not found."
            return (row[0], row[1], row[2], row[3])
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    res = await loop.run_in_executor(None, _sync_work)
    if isinstance(res, str):
        return res
    name, prompt, r_type, severity = res
    if r_type != "simple":
        return f"Only 'simple' routines can be manually triggered with this tool. This is type {r_type}."
    
    # Actually run it
    from core.routines_scheduler import _run_simple_routine
    # Need to trigger it via background task so it doesn't block
    asyncio.create_task(_run_simple_routine(user_id, rid, name, prompt, severity))
    return f"Triggered routine '{name}' in the background."

async def _exec_check_reading_status(args: dict, user_id: str) -> str:
    db_path = get_settings().db_path

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            cur = conn.cursor()
            title = args.get("title", "").strip().lower()
            if title:
                cur.execute(
                    "SELECT title, author, status, progress_pct FROM reading_shelf WHERE user_id = ? AND lower(title) LIKE ?",
                    (user_id,
                     f"%{title}%"))
                rows = cur.fetchall()
                if not rows:
                    return f"I couldn't find '{args['title']}' on your reading shelf."
                r = rows[0]
                return f"'{r[0]}' by {r[1]} is currently marked as '{r[2]}' with {r[3]}% progress."
            else:
                cur.execute(
                    "SELECT title, status FROM reading_shelf WHERE user_id = ? AND status = 'reading'",
                    (user_id,
                     ))
                rows = cur.fetchall()
                if not rows:
                    return "You aren't currently reading anything on your shelf."
                reading_list = ", ".join([r[0] for r in rows])
                return f"You are currently reading: {reading_list}."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_sync_kindle(args: dict, user_id: str) -> str:
    db_path = "data/reading.db"
    os.makedirs(os.path.dirname(db_path), exist_ok=True)

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            cur = conn.cursor()
            cur.execute("""
                CREATE TABLE IF NOT EXISTS kindle_books (
                    id INTEGER PRIMARY KEY,
                    asin TEXT UNIQUE,
                    title TEXT,
                    author TEXT,
                    sync_date TEXT
                )
            """)
            books = args.get("books", [])
            if not books:
                books = [{"asin": "SYNC_PLACEHOLDER",
                          "title": "Manual Sync Run", "author": "System"}]
            added = 0
            sync_date = datetime.now(timezone.utc).isoformat()
            for b in books:
                try:
                    cur.execute(
                        "INSERT OR IGNORE INTO kindle_books (asin, title, author, sync_date) VALUES (?, ?, ?, ?)",
                        (b.get("asin"), b.get("title"), b.get("author"), sync_date)
                    )
                    if cur.rowcount > 0:
                        added += 1
                except Exception:
                    continue
            conn.commit()
            return f"Kindle sync complete. Processed {len(books)} books ({added} new)."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


def _get_commerce_db():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    import os
    db_url = os.environ.get("COMMERCE_DB_URL", "sqlite:///./data/commerce.db")
    engine = create_engine(db_url)
    Session = sessionmaker(bind=engine)
    return Session()


async def _exec_search_commerce_products(args: dict, user_id: str) -> str:
    db = None
    try:
        from commercial_inventory.management import get_workspaces_for_user, get_products, get_or_create_biz_user

        db = _get_commerce_db()
        biz_user = get_or_create_biz_user(
            db, external_user_id=user_id, email=user_id)
        workspaces = get_workspaces_for_user(db, biz_user)
        if not workspaces:
            return "You do not have any active store workspaces configured."

        query = args.get('query', '').lower()
        results = []
        for ws in workspaces:
            products = get_products(db, biz_user, str(ws.id))
            for p in products:
                if query in p.name.lower() or query in str(p.sku).lower():
                    results.append(
                        f"{p.name} (SKU: {p.sku}) - {p.stock_qty} in stock at ${p.unit_price}")

        if not results:
            return f"No products found matching '{query}'."
        return "\n".join(results)
    except Exception as exc:
        return f"Error searching products: {exc}"
    finally:
        if db is not None:
            db.close()


async def _exec_create_commerce_sale(args: dict, user_id: str) -> str:
    db = None
    try:
        from commercial_inventory.management import get_workspaces_for_user, get_products, get_or_create_biz_user, create_sale, LineItemIn
        from commercial_inventory.models import Customer

        db = _get_commerce_db()
        biz_user = get_or_create_biz_user(
            db, external_user_id=user_id, email=user_id)
        workspaces = get_workspaces_for_user(db, biz_user)
        if not workspaces:
            return "You do not have any active store workspaces configured."

        ws = workspaces[0]  # default to first workspace for voice commands
        products = get_products(db, biz_user, str(ws.id))

        product_query = args['product_id'].lower()
        target_product = next((p for p in products if p.sku.lower(
        ) == product_query or p.name.lower() == product_query or str(p.id) == product_query), None)

        if not target_product:
            return f"Could not find a product matching '{args['product_id']}' to sell."

        if target_product.stock_qty < args['quantity']:
            return f"Insufficient stock for {target_product.name}. You only have {target_product.stock_qty} units available."

        customer_id = None
        if args.get('customer_name'):
            # naive search
            cust = db.query(Customer).filter(
                Customer.workspace_id == str(ws.id)).first()
            # for perfection, let's just create if not exists
            if not cust:
                cust = Customer(
                    workspace_id=str(
                        ws.id),
                    name=args['customer_name'])
                db.add(cust)
                db.flush()
            customer_id = str(cust.id)

        line_items = [
            LineItemIn(
                product_id=str(
                    target_product.id), qty=args['quantity'], unit_price=float(
                    target_product.unit_price or 0.0))]
        sale = create_sale(db,
                           biz_user,
                           str(ws.id),
                           line_items,
                           customer_id=customer_id,
                           notes="Created via Voice Assistant",
                           deduct_stock=True)

        from commercial_inventory.models import SaleStatus
        sale.status = SaleStatus.COMPLETED
        db.commit()

        return f"Successfully logged sale of {args['quantity']}x {target_product.name}. Remaining stock: {target_product.stock_qty}."
    except Exception as exc:
        return f"Failed to log sale: {exc}"
    finally:
        if db is not None:
            db.close()


async def _exec_trigger_n8n(args: dict, user_id: str) -> str:
    try:
        from providers.automation.n8n_client import build_n8n_client
        client = build_n8n_client()
        if not client.enabled:
            return "n8n automation is currently disabled in your settings."

        # type: ignore
        success = await client.trigger_workflow(args['workflow_id'], args.get('data'))  # type: ignore
        if success:
            return f"Successfully triggered n8n workflow '{args['workflow_id']}'."
        else:
            return f"Failed to trigger n8n workflow '{args['workflow_id']}'. Check if n8n is running."
    except Exception as exc:
        return f"Error triggering n8n: {exc}"


async def _exec_generate_business_report(args: dict, user_id: str) -> str:
    from commercial_inventory.management import get_workspaces_for_user, get_sales, get_or_create_biz_user
    from datetime import datetime, timedelta

    db = _get_commerce_db()
    try:
        biz_user = get_or_create_biz_user(
            db, external_user_id=user_id, email=user_id)
        workspaces = get_workspaces_for_user(db, biz_user)
        if not workspaces:
            return "No store data available to generate a report."

        days = args.get('days', 30)
        cutoff = datetime.now() - timedelta(days=days)

        total_revenue = 0.0
        total_sales = 0
        top_products = {}  # type: ignore

        for ws in workspaces:
            sales = get_sales(db, biz_user, str(ws.id))
            for s in sales:
                if s.created_at and s.created_at >= cutoff:
                    total_revenue += float(s.total or 0)
                    total_sales += 1
                    for li in s.line_items:
                        name = li.product.name if li.product else "Unknown"
                        top_products[name] = top_products.get(name, 0) + li.qty

        sorted_products = sorted(
            top_products.items(),
            key=lambda x: x[1],
            reverse=True)[
            :3]
        prod_str = ", ".join(
            [f"{name} ({qty} units)" for name, qty in sorted_products])

        report = (
            f"Business Report (Last {days} days):\n"
            f"- Total Sales: {total_sales}\n"
            f"- Total Revenue: ${total_revenue:,.2f}\n"
            f"- Top Products: {prod_str if prod_str else 'N/A'}"
        )
        return report
    finally:
        db.close()


async def _exec_web_search(args: dict, user_id: str) -> str:
    try:
        from providers.web.search import build_search_provider
        provider = build_search_provider()
        return await provider.search(args["query"])
    except Exception as exc:
        logger.error("Web search tool failed: %s", exc)
        return f"I tried to search the web for '{args['query']}', but encountered an issue: {str(exc)}"


async def _exec_search_emails(args: dict, user_id: str) -> str:
    try:
        from providers.google.gmail import build_gmail_provider
        provider = build_gmail_provider(user_id=user_id)

        query = args.get("query", "is:unread")
        max_results = args.get("max_results", 3)

        emails = await provider.search_messages(query, max_results=max_results)
        if not emails:
            return f"I searched your Gmail for '{query}' but didn't find any matching messages."

        summaries = []
        for i, em in enumerate(emails):
            snippet = em.get("snippet", "No snippet.")
            subject = em.get("subject", "No subject")
            sender = em.get("from", "Unknown sender")
            summaries.append(
                f"{i + 1}. From: {sender}\n   Subject: {subject}\n   Snippet: {snippet}")

        header = f"Found {len(summaries)} emails for '{query}':"
        return header + "\n\n" + "\n\n".join(summaries)

    except Exception as exc:
        logger.error("Gmail tool failed: %s", exc)
        return f"I tried to read your emails, but encountered an issue: {str(exc)}. Make sure Google is linked in Settings."


async def _exec_get_weather(args: dict, user_id: str) -> str:
    try:
        from providers.google.maps import build_maps_provider
        from providers.feeds.weather import get_weather_report

        location = args["location"]
        units = args.get("units", "celsius")

        # 1. Geocode location name to lat/lon
        maps = build_maps_provider()
        geo = await maps.geocode(location)
        if not geo:
            return f"I couldn't find a place called '{location}'."

        lat = geo["geometry"]["location"]["lat"]
        lon = geo["geometry"]["location"]["lng"]
        addr = geo.get("formatted_address", location)

        # 2. Fetch weather
        report = await get_weather_report(lat, lon, units)

        return f"Weather for {addr}:\n{report}"

    except Exception as exc:
        logger.error("Weather tool failed: %s", exc)
        return f"I tried to check the weather for '{args['location']}', but encountered an issue: {str(exc)}"


async def _exec_generate_image(args: dict, user_id: str) -> str:
    """Generate an image via SDProvider and return base64 data."""
    try:
        from providers.image.sd_provider import SDProvider
        import base64

        provider = SDProvider()
        img_bytes = await provider.generate(
            prompt=args["prompt"],
            negative_prompt=args.get(
                "negative_prompt",
                "low quality, blurry, distorted"),
        )

        b64 = base64.b64encode(img_bytes).decode("utf-8")
        # Prefix so the frontend can easily identify it
        return f"IMAGE_GEN_SUCCESS:data:image/png;base64,{b64}"

    except Exception as exc:
        logger.error("Image generation tool failed: %s", exc)
        return f"I tried to generate the image, but encountered an issue: {str(exc)}"


async def _exec_search_google_books(args: dict, user_id: str) -> str:
    try:
        from providers.google.books import get_books_provider
        provider = get_books_provider()

        query = args["query"]
        if not provider.is_connected(user_id):
            return "Your Google Books account is not linked. Please connect it in Settings."

        library = await provider.get_library(user_id)
        # Search in library
        matches = [
            b for b in library if query.lower() in b.title.lower() or any(
                query.lower() in a.lower() for a in b.authors)]

        if not matches:
            return f"I couldn't find any books matching '{query}' in your library."

        lines = [f"Found {len(matches)} book(s) in your library:"]
        for b in matches[:5]:
            authors = ", ".join(b.authors)
            lines.append(
                f"- {b.title} by {authors} ({int(b.progress_pct)}% read, status: {b.status})")

        return "\n".join(lines)
    except Exception as exc:
        logger.error("Google Books tool failed: %s", exc)
        return f"I tried to search your Google Books, but encountered an error: {str(exc)}"


async def _exec_add_google_task(args: dict, user_id: str) -> str:
    try:
        from providers.google.tasks import build_tasks_provider
        provider = build_tasks_provider(user_id)

        title = args["title"]
        notes = args.get("notes")

        await provider.create_task(title=title, notes=notes)
        return f"Successfully added task: '{title}' to your Google Tasks."
    except Exception as exc:
        logger.error("Google Tasks add failed: %s", exc)
        return f"I tried to add the task '{args['title']}' to Google Tasks, but encountered an error: {str(exc)}"


async def _exec_list_google_tasks(args: dict, user_id: str) -> str:
    try:
        from providers.google.tasks import build_tasks_provider
        provider = build_tasks_provider(user_id)

        show_completed = args.get("show_completed", False)
        tasks = await provider.get_tasks(show_completed=show_completed)

        if not tasks:
            return "You don't have any tasks in your main Google Tasks list."

        lines = ["Your Google Tasks:"]
        for t in tasks[:10]:
            status = "✓" if t.get("status") == "completed" else "○"
            lines.append(f"{status} {t['title']}")

        return "\n".join(lines)
    except Exception as exc:
        logger.error("Google Tasks list failed: %s", exc)
        return f"I tried to retrieve your Google Tasks, but encountered an error: {str(exc)}"


async def get_upcoming_events(
        user_id: str, hours_ahead: int = 8) -> list[dict]:
    """
    Standalone helper to fetch calendar events for the near future.
    Used by the startup briefing feature.
    """
    try:
        from providers.google.calendar import build_calendar_provider
        from datetime import datetime, timedelta, timezone

        provider = build_calendar_provider(user_id=user_id)

        # We query 1 day to be safe, then filter in memory
        events = await provider.get_upcoming_events(days_ahead=1, max_results=10)

        if not events:
            return []

        now = datetime.now(timezone.utc)
        cutoff = now + timedelta(hours=hours_ahead)

        results = []
        for e in events:
            start_raw = e.get("start", {})
            dt_str = start_raw.get("dateTime") or start_raw.get("date")
            if not dt_str:
                continue

            try:
                # Handle both ISO formats
                start_dt = datetime.fromisoformat(
                    dt_str.replace("Z", "+00:00"))
                if start_dt.tzinfo is None:
                    start_dt = start_dt.replace(tzinfo=timezone.utc)

                if now <= start_dt <= cutoff:
                    results.append({
                        "title": e.get("summary", "Untitled"),
                        "time": start_dt.isoformat(),
                        "location": e.get("location", "")
                    })
            except (ValueError, TypeError):
                continue

        return results
    except Exception as exc:
        logger.debug("get_upcoming_events failed: %s", exc)
        return []


def _get_vault_store():
    """Best-effort: get the live store for vault indexing."""
    try:
        from main import get_app
        app = get_app()
        if app:
            return app.state.memory_manager._store
    except Exception:
        pass
    return None


async def _exec_save_vault_note(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        root = args.get("root", "personal")
        title = args["title"]
        content = args["content"]
        if not title.endswith(".md"):
            title += ".md"
        virtual_path = f"{root}/{title}"
        provider = VaultProvider(store=_get_vault_store())
        await provider.write_note(user_id, virtual_path, content)
        return f"Note '{args['title']}' saved to your {root} vault."
    except Exception as exc:
        logger.error("save_vault_note failed: %s", exc)
        return f"Failed to save note '{args.get('title')}': {exc}"


async def _exec_read_vault_note(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        root = args.get("root", "personal")
        title = args["title"]
        if not title.endswith(".md"):
            title += ".md"
        virtual_path = f"{root}/{title}"
        provider = VaultProvider()
        content = await provider.read_note(user_id, virtual_path)
        if len(content) > 3000:
            content = content[:3000] + "\n\n[... note truncated ...]"
        return content
    except FileNotFoundError:
        return f"No note named '{args['title']}' found in the {args.get('root', 'personal')} vault."
    except Exception as exc:
        logger.error("read_vault_note failed: %s", exc)
        return f"Failed to read note '{args.get('title')}': {exc}"


async def _exec_search_vault(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        provider = VaultProvider(store=_get_vault_store())
        results = await provider.search_text(user_id, args["query"])
        if not results:
            return f"No notes found matching '{args['query']}'."
        lines = [
            f"- {r.get('title', r['virtual_path'])} ({r['virtual_path']})" for r in results[:10]]
        return f"Found {len(results)} note(s):\n" + "\n".join(lines)
    except Exception as exc:
        logger.error("search_vault failed: %s", exc)
        return f"Vault search failed: {exc}"


async def _exec_code_interpreter(args: dict, user_id: str) -> str:
    try:
        from core.code_interpreter import run_code
        return await run_code(args["code"])
    except Exception as exc:
        logger.error("code_interpreter failed: %s", exc)
        return f"Failed to run code: {exc}"


async def _exec_mow_command(args: dict, user_id: str) -> str:
    try:
        from api.routes.vector_fleet import queue_command, get_fleet_state, get_first_unit_id

        command = args["command"]
        unit_id = args.get("unit_id") or get_first_unit_id()

        if not unit_id:
            return (
                "No mower units are registered yet. "
                "Make sure Voyager is running and has connected to River Song."
            )

        fleet = get_fleet_state()
        state = fleet.get(unit_id, {})
        last_seen = state.get("last_seen")
        import time
        online = last_seen and (time.time() - last_seen) < 30

        queued = queue_command(unit_id, command, {})
        if not queued:
            return f"Could not queue '{command}' — unit '{unit_id}' is unknown."

        label = {
            "mow_start": "start mowing",
            "mow_stop": "stop mowing",
            "return_home": "return to dock",
            "estop": "EMERGENCY STOP",
            "estop_reset": "reset the E-stop",
        }.get(command, command)

        if online:
            return f"Command queued: {label}. Voyager will execute it on the next poll (within 100 ms)."
        else:
            ago = f"{
                round(
                    time.time() -
                    last_seen)}s ago" if last_seen else "never"
            return (
                f"Command queued: {label}. "
                f"Note: Voyager was last seen {ago} and may be offline. "
                "It will pick up the command when it reconnects."
            )
    except Exception as exc:
        logger.error("mow_command failed: %s", exc)
        return f"Failed to send mower command: {exc}"

async def _exec_set_timer(args: dict, user_id: str) -> str:
    label = args.get("label", "Timer")
    duration = int(args.get("duration_seconds", 60))
    
    async def _timer_task():
        await asyncio.sleep(duration)
        from api.routes.culinary import _ws_manager
        from core.family import resolve_module_owner
        uid = await resolve_module_owner(user_id, "culinary")
        # In culinary, household ID is usually needed for broadcast. Wait, _ws_manager broadcasts to household_id.
        # So we need to get household_id.
        from sqlalchemy.orm import Session
        from api.routes.culinary import get_db, _get_household
        
        # We need a new DB session inside the background task since the current one might be closed
        from database.core import engine
        from sqlalchemy.orm import sessionmaker
        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
        
        db = SessionLocal()
        try:
            hh = _get_household(db, uid)
            await _ws_manager.broadcast(hh.id, "timer_fired", {"label": label, "duration": duration})
        except Exception as e:
            logger.error(f"Error in timer task: {e}")
        finally:
            db.close()
            
    asyncio.create_task(_timer_task())
    return f"Timer '{label}' set for {duration} seconds."

async def _resolve_vehicle(query: str, user_id: str):
    from vehicles.management import get_vehicles
    from core.family import resolve_module_owner
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    owner_id = await resolve_module_owner(user_id, "maintenance")
    try:
        vehicles = get_vehicles(db, owner_id)
        if not vehicles:
            return None
        # simple fuzzy match
        query = query.lower()
        for v in vehicles:
            if v.nickname and query in v.nickname.lower(): return v.id
            if v.make and query in v.make.lower(): return v.id
            if v.model and query in v.model.lower(): return v.id
        # return first if only one
        if len(vehicles) == 1:
            return vehicles[0].id
        return None
    finally:
        db.close()

async def _exec_get_vehicle_status(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from api.routes.vehicles import get_maintenance_timeline
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        from core.family import resolve_module_owner
        owner_id = await resolve_module_owner(user_id, "maintenance")
        tl = get_maintenance_timeline(str(vid), None, None, db, owner_id)
        return str(tl)
    except Exception as e:
        return f"Error: {e}"
    finally:
        db.close()

async def _exec_get_vehicle_spec(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from vehicles.models import VehicleCheckPoint
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        cps = db.query(VehicleCheckPoint).filter(VehicleCheckPoint.vehicle_id == str(vid)).all()
        q = args.get("item", "").lower()
        for cp in cps:
            if q in cp.description.lower():
                return f"Specs for {cp.description}: Torque {cp.torque_ft_lb} ft-lb / {cp.torque_nm} nm, Fluid {cp.fluid_volume} {cp.expected_spec}"
        return "Spec not found."
    finally:
        db.close()

async def _exec_query_vehicle_manual(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from providers.rag.rag_provider import RAGProvider
    rag = RAGProvider()
    res = await rag.query_documents(args.get("question", ""), where={"vehicle_id": str(vid)}, n_results=3)
    return str(res)

async def _exec_record_odometer(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    val = args.get("value")
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from vehicles.models import UsageReading
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        db.add(UsageReading(vehicle_id=str(vid), value=val, source="manual"))
        db.commit()
        return f"Recorded odometer {val} for vehicle."
    finally:
        db.close()

async def _exec_find_parts(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    # AI lookup verified pipeline
    from core.tools import _exec_web_search
    return await _exec_web_search({"query": f"{args.get('vehicle')} {args.get('job')} OEM part number alternatives price"}, user_id)

async def _exec_remember_fact(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    session_id = context.get("session_id", "unknown_session")
    key = args.get("key", "Fact")
    value = args.get("value")
    if not value: return "Error: value is required."

    from main import get_app
    app = get_app()
    if not app or not hasattr(app.state, "memory_manager"):
        return "Error: Memory manager unavailable."
    
    mm = app.state.memory_manager
    await mm.upsert_fact(user_id=user_id, key=key, value=value, source="explicit", source_kind="conversation", source_ref=session_id)
    return f"Remembered: {key} = {value}"


async def _exec_forget_memory(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    query = args.get("query")
    if not query: return "Error: query is required."
        
    from main import get_app
    app = get_app()
    if not app or not hasattr(app.state, "memory_manager"):
        return "Error: Memory manager unavailable."
    
    mm = app.state.memory_manager
    import uuid
    is_uuid = False
    try:
        uuid.UUID(query)
        is_uuid = True
    except:
        pass
        
    if is_uuid:
        if await mm.delete_fact(query, user_id): return "Deleted fact."
        if await mm.delete_preference(query, user_id): return "Deleted preference."
        if await mm.delete_summary(query, user_id): return "Deleted summary."
        return "Memory ID not found."
        
    matches = await mm.search_memories(user_id, query, limit=5)
    if not matches:
        return "No memories found matching that query."
    if len(matches) == 1:
        m = matches[0]
        if m["type"] == "fact": await mm.delete_fact(m["id"], user_id)
        elif m["type"] == "preference": await mm.delete_preference(m["id"], user_id)
        elif m["type"] == "summary": await mm.delete_summary(m["id"], user_id)
        return f"Deleted {m['type']}: {m['text']}"
    
    out = "Found multiple possible matches. Please call forget_memory again with the exact ID to delete:\n"
    for m in matches:
        out += f"- [{m['id']}] {m['type'].upper()}: {m['text']}\n"
    return out


async def _exec_recall_memory(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    query = args.get("query")
    if not query: return "Error: query is required."
    
    from main import get_app
    app = get_app()
    if not app or not hasattr(app.state, "memory_manager"):
        return "Error: Memory manager unavailable."
        
    mm = app.state.memory_manager
    matches = await mm.search_memories(user_id, query, limit=10)
    if not matches:
        return "No memories found matching that query."
    
    out = "Recalled memories:\n"
    for m in matches:
        out += f"- [{m['id']}] {m['type'].upper()}: {m['text']}\n"
    return out


async def _exec_update_memory(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    query = args.get("query")
    new_value = args.get("new_value")
    if not query or not new_value: return "Error: query and new_value required."
    
    from main import get_app
    app = get_app()
    if not app or not hasattr(app.state, "memory_manager"):
        return "Error: Memory manager unavailable."
        
    mm = app.state.memory_manager
    import uuid
    is_uuid = False
    try:
        uuid.UUID(query)
        is_uuid = True
    except:
        pass
        
    if is_uuid:
        f = await mm._store.get_fact_by_id(user_id, query)
        if f:
            await mm.update_fact(query, user_id, f.key, new_value)
            return "Fact updated."
        p = await mm._store.get_preference_by_id(user_id, query)
        if p:
            await mm.update_preference(query, user_id, p.category, new_value)
            return "Preference updated."
        return "Cannot update summary or memory ID not found."
        
    matches = await mm.search_memories(user_id, query, limit=5)
    if not matches:
        return "No memories found matching that query."
    if len(matches) == 1:
        m = matches[0]
        if m["type"] == "fact":
            f = await mm._store.get_fact_by_id(user_id, m["id"])
            await mm.update_fact(m["id"], user_id, f.key, new_value)
            return "Fact updated."
        elif m["type"] == "preference":
            p = await mm._store.get_preference_by_id(user_id, m["id"])
            await mm.update_preference(m["id"], user_id, p.category, new_value)
            return "Preference updated."
        elif m["type"] == "summary":
            return "Cannot update summary text directly."
    
    out = "Found multiple possible matches. Please call update_memory again with the exact ID to update:\n"
    for m in matches:
        out += f"- [{m['id']}] {m['type'].upper()}: {m['text']}\n"
    return out

async def _get_vault_provider():
    from main import get_app
    app = get_app()
    if not app or not hasattr(app.state, "memory_manager"):
        return None
    from providers.vault.vault_provider import VaultProvider
    return VaultProvider(store=app.state.memory_manager._store)

async def _exec_take_note(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    content = args.get("content")
    if not content:
        return "Error: content is required."
    title = args.get("title", "Untitled Note")
    # Clean title for filename
    import re
    safe_title = re.sub(r"[^A-Za-z0-9 _-]", "", title).strip() or "Note"
    virtual_path = f"personal/{safe_title}.md"
    
    provider = await _get_vault_provider()
    if not provider:
        return "Error: Vault provider unavailable."
    
    # Add provenance frontmatter
    session_id = context.get("session_id", "unknown_session")
    header = f"---\nsource: conversation\nsource_ref: {session_id}\n---\n\n# {title}\n\n"
    
    try:
        await provider.write_note(user_id, virtual_path, header + content)
        return f"Note created at: {virtual_path}"
    except Exception as e:
        return f"Failed to create note: {e}"

async def _exec_append_note(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    title = args.get("title")
    content = args.get("content")
    if not title or not content:
        return "Error: title and content required."
        
    provider = await _get_vault_provider()
    if not provider:
        return "Error: Vault provider unavailable."
        
    # Search for note
    results = await provider.store.search_vault_notes(user_id, title, limit=3)
    if not results:
        return f"No notes found matching '{title}'."
        
    if len(results) > 1 and results[0].get("rank", 0) > -5: 
        matches = [r["virtual_path"] for r in results]
        return f"Found multiple matches. Please use the exact virtual_path to append. Matches: {matches}"
        
    virtual_path = results[0]["virtual_path"]
    try:
        await provider.append_to_note(user_id, virtual_path, "\n" + content)
        return f"Appended to {virtual_path} successfully."
    except Exception as e:
        return f"Failed to append to note: {e}"

async def _exec_journal(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    content = args.get("content")
    if not content:
        return "Error: content is required."
        
    provider = await _get_vault_provider()
    if not provider:
        return "Error: Vault provider unavailable."
        
    try:
        await provider.append_to_daily(user_id, "Journal Entry", content)
        return "Journal entry added to today's daily note."
    except Exception as e:
        return f"Failed to append journal entry: {e}"

async def _exec_find_notes(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    query = args.get("query")
    if not query:
        return "Error: query is required."
        
    provider = await _get_vault_provider()
    if not provider:
        return "Error: Vault provider unavailable."
        
    try:
        results = await provider.store.search_vault_notes(user_id, query, limit=5)
        if not results:
            return f"No notes found for query: {query}"
            
        out = f"Found {len(results)} notes:\n"
        for r in results:
            out += f"- {r['virtual_path']} ({r['title']})\n"
        return out
    except Exception as e:
        return f"Failed to search notes: {e}"

async def _exec_read_note(args: dict, context: dict) -> str:
    user_id = context.get("user_id", "primary_user")
    title = args.get("title")
    if not title:
        return "Error: title or virtual path is required."
        
    provider = await _get_vault_provider()
    if not provider:
        return "Error: Vault provider unavailable."
        
    try:
        # First assume it's a virtual path
        try:
            content = await provider.read_note(user_id, title)
            return f"--- Note: {title} ---\n{content}"
        except Exception:
            # Fallback to search
            results = await provider.store.search_vault_notes(user_id, title, limit=1)
            if not results:
                return f"Note not found: {title}"
            
            vp = results[0]["virtual_path"]
            content = await provider.read_note(user_id, vp)
            return f"--- Note: {vp} ---\n{content}"
    except Exception as e:
        return f"Failed to read note: {e}"
