"""
core/tools.py

Tool definitions and execution logic for River Song AI.
Enables LLMs to perform real-world actions via function calling.
"""

from __future__ import annotations

import logging
import sqlite3
import os
import asyncio
from datetime import datetime, timezone
from typing import Any, Dict, Optional, Tuple

from config.settings import get_settings

logger = logging.getLogger(__name__)

# TOOL_SCHEMAS (and its Playwright extension) live in core/tools_schemas.py;
# re-exported here so existing `from core.tools import TOOL_SCHEMAS` works.
from core.tools_schemas import TOOL_SCHEMAS  # noqa: E402,F401


# =============================================================================
# Tool Executor
# =============================================================================


# Dangerous tools that MUST fail closed if admin policy cannot be verified
DANGEROUS_TOOLS = {
    "run_sandbox_code",
    "code_interpreter",
    "mow_command",
    "browser_click",
    "browser_navigate",
    "trigger_n8n_workflow",
}


async def execute_tool(
        tool_name: str, tool_input: Dict[str, Any], context: Dict[str, Any]) -> str:
    """
    Dispatches a tool call to the appropriate internal provider or database.

    Args:
        tool_name:  The name of the tool chosen by the LLM.
        tool_input: The arguments generated by the LLM.
        context:    Contains metadata like user_id and database connection info.

    Returns:
        A short plain-English success/failure message to be relayed to the user.
    """
    user_id = context.get("user_id", "primary_user")
    logger.info(
        "Executing tool '%s' for user '%s' with input: %s",
        tool_name,
        user_id,
        tool_input)

    # -------------------------------------------------------------------------
    # Hard Choke Point: Admin Tool Toggles & Fail-Closed Policy
    # -------------------------------------------------------------------------
    disabled_tools = context.get("disabled_tools")
    if disabled_tools is None:
        try:
            store = context.get("store")
            if not store:
                from providers.memory.sqlite_store import SQLiteStore
                store = SQLiteStore()
            admin_config = await store.get_admin_config()
            disabled_tools = set(admin_config.get("disabled_tools", []))
        except Exception as exc:
            logger.error("Failed to load admin tool policy in execute_tool: %s", exc)
            if tool_name in DANGEROUS_TOOLS:
                return f"Security Error: Tool '{tool_name}' is disabled (failed closed: admin security policy could not be verified)."
            disabled_tools = set()

    if tool_name in disabled_tools:
        logger.warning("Blocked execution of disabled tool '%s' for user '%s'", tool_name, user_id)
        return f"Tool '{tool_name}' is currently disabled by administrative security policy."

    try:
        if tool_name == "remember_fact":
            return await _exec_remember_fact(tool_input, context)
        elif tool_name == "forget_memory":
            return await _exec_forget_memory(tool_input, context)
        elif tool_name == "recall_memory":
            return await _exec_recall_memory(tool_input, context)
        elif tool_name == "update_memory":
            return await _exec_update_memory(tool_input, context)
        elif tool_name == "take_note":
            return await _exec_take_note(tool_input, context)
        elif tool_name == "append_note":
            return await _exec_append_note(tool_input, context)
        elif tool_name == "journal":
            return await _exec_journal(tool_input, context)
        elif tool_name == "find_notes":
            return await _exec_find_notes(tool_input, context)
        elif tool_name == "read_note":
            return await _exec_read_note(tool_input, context)
        elif tool_name == "deep_research":
            return await _exec_deep_research(
                tool_input, user_id, session_id=(context or {}).get("session_id"))

        elif tool_name == "create_calendar_event":
            return await _exec_calendar_event(tool_input, user_id)

        elif tool_name == "add_asset":
            return await _exec_add_asset(tool_input, user_id)
        elif tool_name == "find_asset":
            return await _exec_find_asset(tool_input, user_id)
        elif tool_name == "asset_summary":
            return await _exec_asset_summary(tool_input, user_id)
        elif tool_name == "registry_health":
            return await _exec_registry_health(tool_input, user_id)
        elif tool_name == "warranty_check":
            return await _exec_warranty_check(tool_input, user_id)

        elif tool_name == "add_shopping_list_item":
            return await _exec_add_shopping_list(tool_input, user_id)

        elif tool_name == "play_media":
            return await _exec_play_media(tool_input, user_id)

        elif tool_name == "media_control":
            return await _exec_media_control(tool_input, user_id)

        elif tool_name == "announce":
            return await _exec_announce(tool_input, user_id)

        elif tool_name in ("read_shopping_list", "get_shopping_list"):
            return await _exec_read_shopping_list(tool_input, user_id)

        elif tool_name == "set_reminder":
            return await _exec_set_reminder(tool_input, user_id)
            
        elif tool_name == "set_timer":
            return await _exec_set_timer(tool_input, user_id)

        elif tool_name == "control_device":
            return await _exec_control_device(tool_input, user_id)

        elif tool_name == "alias_device":
            return await _exec_alias_device(tool_input, user_id)

        elif tool_name == "log_vehicle_maintenance":
            # type: ignore
            return await _exec_vehicle_maintenance(tool_input, context)  # type: ignore

        elif tool_name == "get_vehicle_status": return await _exec_get_vehicle_status(tool_input, user_id)
        elif tool_name == "get_vehicle_spec": return await _exec_get_vehicle_spec(tool_input, user_id)
        elif tool_name == "query_vehicle_manual": return await _exec_query_vehicle_manual(tool_input, user_id)
        elif tool_name == "record_odometer": return await _exec_record_odometer(tool_input, user_id)
        elif tool_name == "find_parts": return await _exec_find_parts(tool_input, user_id)
        elif tool_name == "list_vehicles":
            return await _exec_list_vehicles(tool_input, context)

        elif tool_name == "add_recipe_to_library":
            return await _exec_add_recipe(tool_input, user_id)

        elif tool_name == "create_routine":
            return await _exec_create_routine(tool_input, user_id)
        elif tool_name == "list_routines":
            return await _exec_list_routines(user_id)
        elif tool_name == "update_routine":
            return await _exec_update_routine(tool_input, user_id)
        elif tool_name == "delete_routine":
            return await _exec_delete_routine(tool_input, user_id)
        elif tool_name == "run_routine_now":
            return await _exec_run_routine_now(tool_input, user_id)

        elif tool_name == "check_reading_status":
            return await _exec_check_reading_status(tool_input, user_id)

        elif tool_name == "sync_kindle_library":
            return await _exec_sync_kindle(tool_input, user_id)

        elif tool_name == "search_commerce_products":
            return await _exec_search_commerce_products(tool_input, user_id)

        elif tool_name == "create_commerce_sale":
            return await _exec_create_commerce_sale(tool_input, user_id)

        elif tool_name == "trigger_n8n_workflow":
            return await _exec_trigger_n8n(tool_input, user_id)

        elif tool_name == "generate_business_report":
            return await _exec_generate_business_report(tool_input, user_id)

        elif tool_name == "web_search":
            return await _exec_web_search(tool_input, user_id)

        elif tool_name == "search_emails":
            return await _exec_search_emails(tool_input, user_id)

        elif tool_name == "get_weather":
            return await _exec_get_weather(tool_input, user_id)

        elif tool_name == "generate_image":
            return await _exec_generate_image(tool_input, user_id)

        elif tool_name == "search_google_books":
            return await _exec_search_google_books(tool_input, user_id)

        elif tool_name == "add_google_task":
            return await _exec_add_google_task(tool_input, user_id)

        elif tool_name == "list_google_tasks":
            return await _exec_list_google_tasks(tool_input, user_id)

        elif tool_name == "save_vault_note":
            return await _exec_save_vault_note(tool_input, user_id)

        elif tool_name == "read_vault_note":
            return await _exec_read_vault_note(tool_input, user_id)

        elif tool_name == "search_vault":
            return await _exec_search_vault(tool_input, user_id)

        elif tool_name == "code_interpreter":
            return await _exec_code_interpreter(tool_input, user_id)

        elif tool_name in ("browser_navigate", "browser_extract_text",
                           "browser_click", "browser_screenshot",
                           "browser_vision_on_page"):
            # Q3#13 — Playwright browser tools. Flag-gated; the provider
            # short-circuits when disabled.
            from providers.web.playwright_browser import PLAYWRIGHT_TOOL_DISPATCH
            fn = PLAYWRIGHT_TOOL_DISPATCH.get(tool_name)
            if fn is None:
                return f"Unknown browser tool: {tool_name}"
            return await fn(tool_input or {})

        elif tool_name == "mow_command":
            return await _exec_mow_command(tool_input, user_id)

        elif tool_name == "design_3d_model":
            return await _exec_design_3d_model(tool_input, user_id)

        elif tool_name == "run_sandbox_code":
            return await _exec_run_sandbox_code(tool_input, user_id)

        elif tool_name == "render_diagram":
            return await _exec_render_diagram(tool_input, user_id)

        else:
            return f"Unknown tool '{tool_name}' requested."

    except Exception as exc:
        logger.error(
            "Unexpected error executing tool '%s': %s",
            tool_name,
            exc)
        return f"Tool execution failed due to an internal error: {exc}"


async def _exec_deep_research(args: dict, user_id: str,
                              session_id: str | None = None) -> str:
    try:
        query = args.get("query", "").strip()
        if not query:
            return "Please provide a query for deep research."
            
        from core.deep_research import decompose_query, run_deep_research
        from config.settings import get_settings
        
        if not getattr(get_settings(), "deep_research_enabled", False):
            return "Deep Research is disabled in settings."
            
        # Try to estimate complexity
        sub_queries = await decompose_query(query, count=2)
        count = len(sub_queries)
        
        # Quick: run inside the turn. Big: enqueue background job.
        
        def _get_store():
            try:
                from main import get_app
                app = get_app()
                if app:
                    return app.state.memory_manager._store
            except Exception:
                pass
            return None
            
        store = _get_store()
        if not store:
            return "Cannot run research without document store."
            
        if count <= 2:
            # Inline execution
            try:
                result = await run_deep_research(query, user_id=user_id, store=store)
                report = result.get("report", "")
                doc_id = result.get("document_id")
                return f"I've completed the deep research. The report is saved to your Documents (ID: {doc_id}).\n\n{report}"
            except Exception as e:
                logger.error(f"Inline deep research failed: {e}")
                return f"Deep research encountered an error: {e}"

        # Big: background execution
        import asyncio
        
        async def background_research():
            try:
                result = await run_deep_research(query, user_id=user_id, store=store)
                logger.info(f"Background research complete for '{query}': doc_id={result.get('document_id')}")
                
                # Append to the session
                target_session = args.get("session_id") or session_id
                if target_session:
                    report = result.get("report", "Research complete.")
                    doc_id = result.get("document_id")
                    
                    content = f"I've finished the deep research on '{query}'.\n\n"
                    if doc_id:
                        content += f"I've saved the full report to your Documents.\n\n"
                    content += report
                        
                    await store.save_chat_message(
                        user_id=user_id,
                        session_id=target_session,
                        role="assistant",
                        content=content
                    )
                    
                    # Try to push via FCM
                    try:
                        from providers.notifier.fcm_notifier import FCMNotifier
                        await FCMNotifier(store).send_notification(
                            user_id=user_id,
                            title="Research Complete",
                            body=f"Your deep research on '{query}' is ready.",
                            data={"session_id": target_session, "doc_id": doc_id or ""}
                        )
                    except Exception as e:
                        logger.debug("Failed to push FCM notification for research: %s", e)
                        
            except Exception as e:
                logger.error(f"Background research failed: {e}")
                
        asyncio.create_task(background_research())
        return f"I'm starting a deep dive on '{query}'. I'll let you know when the report is ready. It will be saved to your documents."
        
    except Exception as exc:
        logger.error("deep_research failed: %s", exc)
        return f"Deep research failed: {exc}"


# -----------------------------------------------------------------------------
# Individual Executors (Private)
# -----------------------------------------------------------------------------

async def _exec_calendar_event(args: dict, user_id: str) -> str:
    try:
        from providers.google.calendar import build_calendar_provider
        from datetime import datetime

        provider = build_calendar_provider(user_id=user_id)

        # Parse date and time
        date_obj = datetime.strptime(args["date"], "%Y-%m-%d").date()
        time_obj = datetime.strptime(args["time"], "%H:%M").time()
        start_dt = datetime.combine(date_obj, time_obj)

        await provider.create_event(
            summary=args["title"],
            start_dt=start_dt,
            end_dt=None,  # Provider defaults to +1 hour, which is fine
        )
        return f"Successfully scheduled '{args['title']}' for {args['date']} at {args['time']} on your Google Calendar."
    except Exception as exc:
        logger.error("Calendar tool failed: %s", exc)
        return f"I tried to create the calendar event for '{args['title']}', but encountered an issue: {str(exc)}. Make sure Google is linked in Settings."


async def _exec_add_asset(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.management import create_item, get_or_create_inv_user, get_homes_for_user, create_home, ItemCategory
        from inventory.models import InvHome
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            homes = get_homes_for_user(db, str(inv_user.id))
            
            home = None
            if args.get('home'):
                home = next((h for h in homes if h.name.lower() == args['home'].lower()), None)
            
            if not home:
                if not homes:
                    home = create_home(db, inv_user, "Primary Residence", "")
                else:
                    home = homes[0]
            
            cat_str = args.get('category', 'OTHER').upper()
            try:
                cat = ItemCategory(cat_str)
            except ValueError:
                cat = ItemCategory.OTHER
                
            item = create_item(
                db=db, 
                user_id=str(inv_user.id), 
                home_id=str(home.id), 
                name=args['name'],
                location=args.get('location', ''),
                category=cat,
                description=args.get('details', '')
            )
            return f"Added {item.name} to the inventory at {item.location} in {home.name}."
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_find_asset(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            
            query_str = args.get('query', '').lower()
            
            items = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id).all()
            matches = []
            for item in items:
                if (query_str in item.name.lower() or 
                    (item.ein and query_str in item.ein.lower()) or 
                    (item.serial_number and query_str in item.serial_number.lower())):
                    matches.append(item)
                    
            if not matches:
                return f"No assets found matching '{query_str}'."
            
            lines = [f"Found {len(matches)} matching asset(s):"]
            for m in matches:
                audit_info = f"Last seen: {m.last_audit_date.date()}" if m.last_audit_date else "Never audited"
                home_name = m.home.name if m.home else "Unknown Home"
                lines.append(f"- {m.name} (Location: {m.location} in {home_name}). {audit_info}.")
            return "\n".join(lines)
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_asset_summary(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        from decimal import Decimal
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            scope = args.get('scope', '').lower()
            
            items = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id).all()
            
            if scope and 'home' not in scope and 'room' not in scope and 'categor' not in scope:
                items = [i for i in items if scope in i.name.lower() or (i.category and scope in i.category.value.lower()) or (i.location and scope in i.location.lower()) or (i.home and scope in i.home.name.lower())]
                
            total_count = len(items)
            total_value = sum((i.replacement_cost or i.purchase_price or Decimal('0.0')) for i in items)
            
            return f"Asset Summary: You have {total_count} items matching your criteria, with a total estimated replacement value of ${total_value:,.2f}."
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_registry_health(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            home_filter = args.get('home')
            
            query = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id)
            if home_filter:
                query = query.filter(InvHome.name.ilike(f"%{home_filter}%"))
                
            items = query.all()
            missing_photos = sum(1 for i in items if not i.attachments)
            missing_serials = sum(1 for i in items if not i.serial_number)
            missing_values = sum(1 for i in items if not i.replacement_cost and not i.purchase_price)
            missing_receipts = sum(1 for i in items if not i.receipt_image_path)
            
            return (f"Registry Health Report (Total Items: {len(items)}):\\n"
                    f"- Missing Photos: {missing_photos}\\n"
                    f"- Missing Serial Numbers: {missing_serials}\\n"
                    f"- Missing Values: {missing_values}\\n"
                    f"- Missing Receipts: {missing_receipts}\\n"
                    f"Please update your stash for better claims readiness.")
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)

async def _exec_warranty_check(args: dict, user_id: str) -> str:
    def _sync_work():
        from api.routes.inventory import get_db as get_inventory_db
        from inventory.models import InventoryItem, InvHome
        from inventory.management import get_or_create_inv_user
        from core.family import resolve_module_owner
        from datetime import date, timedelta
        
        db = next(get_inventory_db())
        try:
            eff_user = resolve_module_owner(user_id, "inventory")
            inv_user = get_or_create_inv_user(db, eff_user, f"{eff_user}@local", eff_user)
            item_name = args.get('item_name')
            days = args.get('expiring_within_days', 30)
            
            query = db.query(InventoryItem).join(InvHome).filter(InvHome.owner_id == inv_user.id)
            if item_name:
                query = query.filter(InventoryItem.name.ilike(f"%{item_name}%"))
                
            items = query.all()
            today = date.today()
            cutoff = today + timedelta(days=days)
            
            if item_name and len(items) == 1:
                item = items[0]
                if not item.warranty_expiry_date:
                    return f"The {item.name} does not have a warranty expiration date recorded."
                status = "expired" if item.warranty_expiry_date < today else "valid"
                return f"The warranty for {item.name} is {status} (expires/expired on {item.warranty_expiry_date.isoformat()})."
                
            expiring_soon = [i for i in items if i.warranty_expiry_date and today <= i.warranty_expiry_date <= cutoff]
            expired = [i for i in items if i.warranty_expiry_date and i.warranty_expiry_date < today]
            
            lines = [f"Warranty Check (Looking ahead {days} days):"]
            lines.append(f"Expiring Soon ({len(expiring_soon)}): " + ", ".join(f"{i.name} ({i.warranty_expiry_date})" for i in expiring_soon) if expiring_soon else "Expiring Soon: None")
            lines.append(f"Already Expired ({len(expired)}): " + ", ".join(f"{i.name}" for i in expired) if expired else "Already Expired: None")
            return "\n".join(lines)
        finally:
            db.close()
            
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


# Stores we are willing to strip off the end of a spoken item. Matching has to
# be against a known name and nothing else: an earlier version also accepted
# "any trailing phrase of two words or fewer", which turned "flour for baking"
# into flour @ Baking, "batteries for the remote" into batteries @ The Remote,
# and "chips for the party" into chips @ The Party -- truncating the item name
# on the way through. A shopping list that quietly renames what you asked for
# is worse than one that never guesses the store.
_SPOKEN_STORE_NAMES = frozenset({
    "walmart", "wal-mart", "costco", "target", "amazon", "kroger",
    "trader joe's", "trader joes", "aldi", "home depot", "homedepot",
    "sams club", "sam's club", "whole foods", "safeway", "publix",
    "heb", "h-e-b", "meijer", "walgreens", "cvs", "lowes", "lowe's",
    "wegmans", "winco", "food lion", "giant", "harris teeter",
})

# Longest known store name, in words -- bounds how much of the tail we even
# look at.
_MAX_STORE_WORDS = max(len(s.split()) for s in _SPOKEN_STORE_NAMES)


def _split_trailing_store(text: str) -> Tuple[str, Optional[str]]:
    """Split "milk at Costco" into ("milk", "Costco").

    Returns the text unchanged with None when the trailing phrase is not a
    store we recognise.
    """
    import re

    m = re.search(
        r"\s+(?:at|from)\s+(?:the\s+)?([A-Za-z0-9\s'\.\-]+?)(?:\s+(?:store|market))?$",
        text,
        re.IGNORECASE,
    )
    if not m:
        return text, None
    candidate = m.group(1).strip()
    if len(candidate.split()) > _MAX_STORE_WORDS:
        return text, None
    if candidate.lower().rstrip(".") not in _SPOKEN_STORE_NAMES:
        return text, None
    remainder = text[:m.start()].strip()
    # "at Costco" on its own is a store, not an item -- keep the original.
    if not remainder:
        return text, None
    return remainder, candidate


async def _exec_add_shopping_list(args: dict, user_id: str) -> str:
    from api.routes.culinary import _Session as SessionLocal, store_display_name
    from culinary.models import Household, ShoppingListItem, ListSource, StoreMapping
    item = args.get("item")
    qty = args.get("quantity")
    unit = args.get("unit")
    store = args.get("store")

    if not item:
        return "Error: item is required."

    def _sync_work():
        from core.family import resolve_module_owner
        from sqlalchemy.exc import IntegrityError

        db = SessionLocal()
        try:
            # The shopping list is household data, and in a shared house the
            # household is owned by "family:<group_id>", not by the speaker.
            # Looking it up by the raw user_id found nothing -- and unlike the
            # HTTP path this one does not create on miss -- so every voice add
            # in a shared household answered "Error: Household not found."
            # The one place the list is easiest to reach was the one place it
            # did not work.
            owner_id = resolve_module_owner(user_id, "culinary")
            hh = db.query(Household).filter(
                Household.owner_id == owner_id).first()
            if not hh:
                # Matches _get_household in api/routes/culinary.py, which
                # creates on miss. Saying "not found" to someone who has
                # simply never opened the Culinary page is a dead end they
                # cannot act on.
                try:
                    hh = Household(owner_id=owner_id)
                    db.add(hh)
                    db.commit()
                    db.refresh(hh)
                except IntegrityError:
                    # Concurrent insert - re-query to get the existing record
                    db.rollback()
                    hh = db.query(Household).filter(
                        Household.owner_id == owner_id).first()
                    if not hh:
                        raise  # Something else went wrong

            # Detect store from text if not explicitly provided
            resolved_store = store_display_name(store)
            clean_item = item.strip()
            if not resolved_store:
                clean_item, spoken_store = _split_trailing_store(clean_item)
                resolved_store = store_display_name(spoken_store)

            # Check store mapping if still no store
            if not resolved_store:
                mapping = db.query(StoreMapping).filter_by(
                    household_id=hh.id, ingredient_name=clean_item.lower()).first()
                if mapping and mapping.store:
                    resolved_store = store_display_name(mapping.store)

            sl_item = ShoppingListItem(
                household_id=hh.id,
                name=clean_item,
                qty=str(qty) if qty not in (None, "") else None,
                unit=unit if unit else None,
                store=resolved_store,
                category="grocery",
                source=ListSource.CHAT,
                added_by=user_id
            )
            db.add(sl_item)
            db.commit()
            return hh.id, clean_item, resolved_store
        finally:
            db.close()

    loop = asyncio.get_running_loop()
    household_id, clean_item, resolved_store = await loop.run_in_executor(None, _sync_work)

    # Everyone else's screen has to learn about it. The HTTP routes broadcast
    # on every mutation; this path wrote straight to the database, so a spoken
    # item sat invisible until someone reloaded -- which for a list whose
    # whole point is being shared is most of the value gone.
    try:
        from api.routes.culinary import _ws_manager
        await _ws_manager.broadcast(household_id, "grocery_updated", {})
    except Exception as exc:
        logger.warning(
            "Shopping list item saved but the household was not notified: %s",
            exc)

    if resolved_store:
        return f"Added '{clean_item}' to your {resolved_store} shopping list."
    return f"Added '{clean_item}' to your shopping list."


async def _exec_read_shopping_list(args: dict, user_id: str) -> str:
    from api.routes.culinary import _Session as SessionLocal
    from culinary.models import Household, ShoppingListItem

    store_filter = (args.get("store") or "").strip()

    def _sync_work():
        from core.family import resolve_module_owner
        db = SessionLocal()
        try:
            owner_id = resolve_module_owner(user_id, "culinary")
            hh = db.query(Household).filter(Household.owner_id == owner_id).first()
            if not hh:
                return []
            q = db.query(ShoppingListItem).filter(
                ShoppingListItem.household_id == hh.id,
                ShoppingListItem.checked_at.is_(None)
            )
            if store_filter:
                q = q.filter(ShoppingListItem.store.ilike(f"%{store_filter}%"))
            # Sort untagged items last explicitly. Bare `store.asc()` puts
            # NULLs first on SQLite and last on Postgres, so the spoken
            # readback changed order with the backend.
            rows = q.order_by(
                ShoppingListItem.store.is_(None).asc(),
                ShoppingListItem.store.asc(),
                ShoppingListItem.created_at.desc(),
            ).all()
            return [(i.name, i.qty, i.unit, i.store) for i in rows]
        finally:
            db.close()

    loop = asyncio.get_running_loop()
    items = await loop.run_in_executor(None, _sync_work)

    if not items:
        if store_filter:
            return f"Your {store_filter} shopping list is currently empty."
        return "Your shopping list is currently empty."

    if store_filter:
        lines = [f"- {qty + ' ' if qty else ''}{unit + ' ' if unit else ''}{name}" for name, qty, unit, _ in items]
        return f"Items on your {store_filter} shopping list:\n" + "\n".join(lines)

    by_store = {}
    for name, qty, unit, st in items:
        st_key = st if st else "General / Any Store"
        by_store.setdefault(st_key, []).append(f"{qty + ' ' if qty else ''}{unit + ' ' if unit else ''}{name}")

    out = ["Your current shopping list:"]
    for st_name, it_list in by_store.items():
        out.append(f"\n**{st_name}**:")
        for it in it_list:
            out.append(f"  • {it}")
    return "\n".join(out)


async def _exec_set_reminder(args: dict, user_id: str) -> str:
    settings = get_settings()
    db_path = settings.db_path

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS reminders (
                    id INTEGER PRIMARY KEY,
                    user_id TEXT,
                    message TEXT,
                    remind_at TEXT,
                    created_at TEXT
                )
            """)
            conn.execute(
                """INSERT INTO reminders (user_id, message, remind_at, created_at) VALUES (?, ?, ?, ?)""",
                (user_id, args['message'], args['datetime_str'],
                 datetime.now(timezone.utc).isoformat())
            )
            conn.commit()
            return f"Reminder set: '{args['message']}' for {args['datetime_str']}."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


async def _exec_control_device(args: dict, user_id: str) -> str:
    try:
        from providers.smart_home.home_assistant import build_ha_client
        from providers.smart_home.device_registry import get_device_registry

        registry = get_device_registry()
        resolved = await registry.resolve(args['device_name'])
        if not resolved:
            return f"I couldn't find a device named '{args['device_name']}' in your registry."

        async with build_ha_client() as client:
            if isinstance(resolved, list):
                await client.execute_action_on_many(resolved, args['action'], args.get('value'))
            else:
                await client.execute_action(resolved, args['action'], args.get('value'))

        return f"Confirmed. Turned {args['action']} the {args['device_name']}."
    except Exception:
        return f"Home Assistant isn't reachable right now — I couldn't turn {args['action']} the {args['device_name']}."


async def _exec_alias_device(args: dict, user_id: str) -> str:
    """
    Updates the ha_entities table to add a new alias to an entity.
    """
    from core.family import is_feature_enabled_for
    if not await is_feature_enabled_for(user_id, "home"):
        return "Home automation features are disabled for your account."

    entity_id = args.get("entity_id")
    alias = args.get("alias")
    if not entity_id or not alias:
        return "Both entity_id and alias must be provided."

    from main import get_app
    app = get_app()
    if not app:
        return "Internal error: app context not found."
    
    store = app.state.memory_manager._store
    try:
        import json
        rows = await store.execute_read_async("SELECT aliases FROM ha_entities WHERE entity_id = ?", (entity_id,))
        if not rows:
            return f"Entity {entity_id} not found in the registry."
            
        current_aliases = json.loads(rows[0]["aliases"])
        if alias not in current_aliases:
            current_aliases.append(alias)
            await store.execute_write_async(
                "UPDATE ha_entities SET aliases = ? WHERE entity_id = ?",
                (json.dumps(current_aliases), entity_id)
            )
            return f"Successfully learned the name '{alias}' for {entity_id}."
        return f"I already know '{alias}' as a name for {entity_id}."
    except Exception as e:
        logger.error("Error aliasing device: %s", e)
        return "Failed to save the new name."


async def _exec_vehicle_maintenance(args: dict, context: dict) -> str:
    user_id = context.get("user_id")
    
    vehicle_id = context.get("vehicle_id")
    if not vehicle_id:
        vehicle_id = await _resolve_vehicle(args.get("vehicle", ""), user_id)
    if not vehicle_id:
        return {"error": "No vehicle_id in context and could not resolve vehicle."}


    def _sync_work():
        from vehicles.management import get_vehicles, create_service_log
        import difflib
        from datetime import datetime, timezone

        db = context.get("db")
        if not db:
            from sqlalchemy import create_engine
            from sqlalchemy.orm import sessionmaker
            engine = create_engine(
                os.environ.get(
                    "VEHICLES_DB_URL",
                    "sqlite:///./data/vehicles.db"))
            db = sessionmaker(bind=engine)()
            close_db = True
        else:
            close_db = False

        # A distinct local name: assigning to `vehicle_id` here would make it
        # local to the whole function and shadow the enclosing-scope value,
        # raising UnboundLocalError on the first read below.
        resolved_id = vehicle_id
        try:
            # If vehicle_id is missing, try to resolve from args
            if not resolved_id:
                vehicle_name = args.get('vehicle_name')
                if not vehicle_name:
                    return {"error": "Must specify a vehicle_name if not already in context."}

                v = _resolve_vehicle_sync(db, user_id, vehicle_name)
                if not v:
                    return {"error": f"Could not find a vehicle matching '{vehicle_name}'."}
                resolved_id = str(v.id)
            else:
                vehicles = get_vehicles(db, user_id)  # type: ignore
                v = next((v for v in vehicles if str(v.id) == resolved_id), None)
                if not v:
                    return {"error": "Vehicle not found."}

            service_type = args.get('service_type', '')
            date_str = args.get('date', datetime.now(timezone.utc).date().isoformat())
            mileage = args.get('mileage')
            cost = args.get('cost')
            notes = args.get('notes', '')

            try:
                service_date = datetime.strptime(date_str, "%Y-%m-%d")
            except ValueError:
                service_date = datetime.now(timezone.utc)

            # Fuzzy match the checkpoint
            checkpoints = {cp.description: cp for cp in v.check_points}
            descriptions = list(checkpoints.keys())

            matches = difflib.get_close_matches(service_type, descriptions, n=1, cutoff=0.6)
            matched_cp = None
            if matches:
                matched_cp = checkpoints[matches[0]]

            check_results = []
            if matched_cp:
                check_results.append({
                    "description": matched_cp.description,
                    "check_point_id": str(matched_cp.id),
                    "status": "pass",
                    "passed": True
                })
                # Update checkpoint explicitly
                if mileage is not None:
                    matched_cp.last_service_odometer = mileage
                matched_cp.last_service_date = service_date
                db.commit()

            log = create_service_log(
                db, user_id, resolved_id,  # type: ignore
                service_date=service_date,
                odometer=mileage,
                service_type=service_type,
                cost=cost,
                notes=notes,
                check_results=check_results
            )
            
            # Record usage reading if mileage provided
            if mileage is not None:
                from vehicles.models import UsageReading, UsageUnit, UsageSource
                ur = UsageReading(
                    vehicle_id=v.id,
                    value=mileage,
                    unit=UsageUnit.MILES,
                    source=UsageSource.SERVICE_LOG,
                    recorded_at=service_date
                )
                db.add(ur)
                db.commit()

            result = {
                "success": True,
                "message": f"Logged '{matched_cp.description if matched_cp else service_type}' at {mileage} miles.",
                "matched_checkpoint": matched_cp.description if matched_cp else None,
                "log_id": str(log.id)
            }
            import json
            return json.dumps(result)
        finally:
            if close_db:
                db.close()

    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)


def _resolve_vehicle_sync(db, user_id, query):
    import difflib
    from api.routes.vehicles import get_vehicles
    vehicles = get_vehicles(db, user_id)
    if not vehicles:
        return None
    
    # Try exact nickname
    for v in vehicles:
        if v.nickname and v.nickname.lower() == query.lower():
            return v
    
    names = {}
    for v in vehicles:
        n1 = v.nickname or ""
        n2 = f"{v.year} {v.make} {v.model}"
        names[n1.lower()] = v
        names[n2.lower()] = v
    
    matches = difflib.get_close_matches(query.lower(), list(names.keys()), n=1, cutoff=0.4)
    if matches:
        return names[matches[0]]
    return vehicles[0] # fallback


def _get_db_for_tools(context):
    db = context.get("db")
    if not db:
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker
        engine = create_engine(os.environ.get("VEHICLES_DB_URL", "sqlite:///./data/vehicles.db"))
        return sessionmaker(bind=engine)(), True
    return db, False


async def _exec_list_vehicles(args: dict, context: dict) -> str:
    user_id = context.get("user_id") or "primary_user"
    def _sync():
        db, close = _get_db_for_tools(context)
        try:
            from api.routes.vehicles import get_vehicles, get_maintenance_timeline
            vehicles = get_vehicles(db, user_id)
            res = []
            for v in vehicles:
                try:
                    tl = get_maintenance_timeline(str(v.id), None, None, db, user_id)
                except Exception:
                    tl = {}
                res.append({
                    "id": str(v.id),
                    "name": v.nickname or f"{v.year} {v.make} {v.model}",
                    "effective_odometer": tl.get("eff_odometer")
                })
            import json
            return json.dumps({"vehicles": res})
        finally:
            if close: db.close()
    return await asyncio.get_running_loop().run_in_executor(None, _sync)




async def _exec_add_recipe(args: dict, user_id: str) -> str:
    settings = get_settings()
    db_path = settings.db_path

    def _sync_work():
        conn = sqlite3.connect(db_path)
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS recipe_stubs (
                    id INTEGER PRIMARY KEY,
                    user_id TEXT,
                    title TEXT,
                    source_url TEXT,
                    notes TEXT,
                    created_at TEXT
                )
            """)
            conn.execute(
                """INSERT INTO recipe_stubs (user_id, title, source_url, notes, created_at)
                   VALUES (?, ?, ?, ?, ?)""",
                (user_id, args['title'], args.get('source_url', ''), args.get(
                    'notes', ''), datetime.now(timezone.utc).isoformat())
            )
            conn.commit()
            return f"Added '{args['title']}' to your culinary library."
        finally:
            conn.close()
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _sync_work)



# Routine / reading / commerce executors live in their own modules
# (god-file #3); re-exported so execute_tool's dispatch is unchanged.
from core.tools_routines import (  # noqa: E402
    _exec_create_routine, _exec_list_routines, _exec_update_routine,
    _exec_delete_routine, _exec_run_routine_now,
)
from core.tools_reading import (  # noqa: E402
    _exec_check_reading_status, _exec_sync_kindle,
)
from core.tools_commerce import (  # noqa: E402
    _get_commerce_db, _exec_search_commerce_products, _exec_create_commerce_sale,
)
async def _exec_trigger_n8n(args: dict, user_id: str) -> str:
    try:
        from providers.automation.n8n_client import build_n8n_client
        client = build_n8n_client()
        if not client.enabled:
            return "n8n automation is currently disabled in your settings."

        # type: ignore
        success = await client.trigger_workflow(args['workflow_id'], args.get('data'))  # type: ignore
        if success:
            return f"Successfully triggered n8n workflow '{args['workflow_id']}'."
        else:
            return f"Failed to trigger n8n workflow '{args['workflow_id']}'. Check if n8n is running."
    except Exception as exc:
        return f"Error triggering n8n: {exc}"


async def _exec_generate_business_report(args: dict, user_id: str) -> str:
    from commercial_inventory.management import get_workspaces_for_user, get_sales, get_or_create_biz_user
    from datetime import datetime, timedelta

    db = _get_commerce_db()
    try:
        biz_user = get_or_create_biz_user(
            db, external_user_id=user_id, email=user_id)
        workspaces = get_workspaces_for_user(db, biz_user)
        if not workspaces:
            return "No store data available to generate a report."

        days = args.get('days', 30)
        cutoff = datetime.now() - timedelta(days=days)

        total_revenue = 0.0
        total_sales = 0
        top_products = {}  # type: ignore

        for ws in workspaces:
            sales = get_sales(db, biz_user, str(ws.id))
            for s in sales:
                if s.created_at and s.created_at >= cutoff:
                    total_revenue += float(s.total or 0)
                    total_sales += 1
                    for li in s.line_items:
                        name = li.product.name if li.product else "Unknown"
                        top_products[name] = top_products.get(name, 0) + li.qty

        sorted_products = sorted(
            top_products.items(),
            key=lambda x: x[1],
            reverse=True)[
            :3]
        prod_str = ", ".join(
            [f"{name} ({qty} units)" for name, qty in sorted_products])

        report = (
            f"Business Report (Last {days} days):\n"
            f"- Total Sales: {total_sales}\n"
            f"- Total Revenue: ${total_revenue:,.2f}\n"
            f"- Top Products: {prod_str if prod_str else 'N/A'}"
        )
        return report
    finally:
        db.close()


async def _exec_web_search(args: dict, user_id: str) -> str:
    try:
        from providers.web.search import build_search_provider
        provider = build_search_provider()
        return await provider.search(args["query"])
    except Exception as exc:
        logger.error("Web search tool failed: %s", exc)
        return f"I tried to search the web for '{args['query']}', but encountered an issue: {str(exc)}"


async def _exec_search_emails(args: dict, user_id: str) -> str:
    try:
        from providers.google.gmail import build_gmail_provider
        provider = build_gmail_provider(user_id=user_id)

        query = args.get("query", "is:unread")
        max_results = args.get("max_results", 3)

        emails = await provider.search_messages(query, max_results=max_results)
        if not emails:
            return f"I searched your Gmail for '{query}' but didn't find any matching messages."

        summaries = []
        for i, em in enumerate(emails):
            snippet = em.get("snippet", "No snippet.")
            subject = em.get("subject", "No subject")
            sender = em.get("from", "Unknown sender")
            summaries.append(
                f"{i + 1}. From: {sender}\n   Subject: {subject}\n   Snippet: {snippet}")

        header = f"Found {len(summaries)} emails for '{query}':"
        return header + "\n\n" + "\n\n".join(summaries)

    except Exception as exc:
        logger.error("Gmail tool failed: %s", exc)
        return f"I tried to read your emails, but encountered an issue: {str(exc)}. Make sure Google is linked in Settings."


async def _exec_get_weather(args: dict, user_id: str) -> str:
    try:
        from providers.google.maps import build_maps_provider
        from providers.feeds.weather import get_weather_report

        location = args["location"]
        units = args.get("units", "celsius")

        # 1. Geocode location name to lat/lon
        maps = build_maps_provider()
        geo = await maps.geocode(location)
        if not geo:
            return f"I couldn't find a place called '{location}'."

        lat = geo["geometry"]["location"]["lat"]
        lon = geo["geometry"]["location"]["lng"]
        addr = geo.get("formatted_address", location)

        # 2. Fetch weather
        report = await get_weather_report(lat, lon, units)

        return f"Weather for {addr}:\n{report}"

    except Exception as exc:
        logger.error("Weather tool failed: %s", exc)
        return f"I tried to check the weather for '{args['location']}', but encountered an issue: {str(exc)}"


async def _exec_generate_image(args: dict, user_id: str) -> str:
    """Generate an image via SDProvider and return base64 data."""
    try:
        from providers.image.sd_provider import SDProvider
        import base64

        provider = SDProvider()
        img_bytes = await provider.generate(
            prompt=args["prompt"],
            negative_prompt=args.get(
                "negative_prompt",
                "low quality, blurry, distorted"),
        )

        b64 = base64.b64encode(img_bytes).decode("utf-8")
        # Prefix so the frontend can easily identify it
        return f"IMAGE_GEN_SUCCESS:data:image/png;base64,{b64}"

    except Exception as exc:
        logger.error("Image generation tool failed: %s", exc)
        return f"I tried to generate the image, but encountered an issue: {str(exc)}"


async def _exec_search_google_books(args: dict, user_id: str) -> str:
    try:
        from providers.google.books import get_books_provider
        provider = get_books_provider()

        query = args["query"]
        if not provider.is_connected(user_id):
            return "Your Google Books account is not linked. Please connect it in Settings."

        library = await provider.get_library(user_id)
        # Search in library
        matches = [
            b for b in library if query.lower() in b.title.lower() or any(
                query.lower() in a.lower() for a in b.authors)]

        if not matches:
            return f"I couldn't find any books matching '{query}' in your library."

        lines = [f"Found {len(matches)} book(s) in your library:"]
        for b in matches[:5]:
            authors = ", ".join(b.authors)
            lines.append(
                f"- {b.title} by {authors} ({int(b.progress_pct)}% read, status: {b.status})")

        return "\n".join(lines)
    except Exception as exc:
        logger.error("Google Books tool failed: %s", exc)
        return f"I tried to search your Google Books, but encountered an error: {str(exc)}"


async def _exec_add_google_task(args: dict, user_id: str) -> str:
    try:
        from providers.google.tasks import build_tasks_provider
        provider = build_tasks_provider(user_id)

        title = args["title"]
        notes = args.get("notes")

        await provider.create_task(title=title, notes=notes)
        return f"Successfully added task: '{title}' to your Google Tasks."
    except Exception as exc:
        logger.error("Google Tasks add failed: %s", exc)
        return f"I tried to add the task '{args['title']}' to Google Tasks, but encountered an error: {str(exc)}"


async def _exec_list_google_tasks(args: dict, user_id: str) -> str:
    try:
        from providers.google.tasks import build_tasks_provider
        provider = build_tasks_provider(user_id)

        show_completed = args.get("show_completed", False)
        tasks = await provider.get_tasks(show_completed=show_completed)

        if not tasks:
            return "You don't have any tasks in your main Google Tasks list."

        lines = ["Your Google Tasks:"]
        for t in tasks[:10]:
            status = "✓" if t.get("status") == "completed" else "○"
            lines.append(f"{status} {t['title']}")

        return "\n".join(lines)
    except Exception as exc:
        logger.error("Google Tasks list failed: %s", exc)
        return f"I tried to retrieve your Google Tasks, but encountered an error: {str(exc)}"


async def get_upcoming_events(
        user_id: str, hours_ahead: int = 8) -> list[dict]:
    """
    Standalone helper to fetch calendar events for the near future.
    Used by the startup briefing feature.
    """
    try:
        from providers.google.calendar import build_calendar_provider
        from datetime import datetime, timedelta, timezone

        provider = build_calendar_provider(user_id=user_id)

        # We query 1 day to be safe, then filter in memory
        events = await provider.get_upcoming_events(days_ahead=1, max_results=10)

        if not events:
            return []

        now = datetime.now(timezone.utc)
        cutoff = now + timedelta(hours=hours_ahead)

        results = []
        for e in events:
            start_raw = e.get("start", {})
            dt_str = start_raw.get("dateTime") or start_raw.get("date")
            if not dt_str:
                continue

            try:
                # Handle both ISO formats
                start_dt = datetime.fromisoformat(
                    dt_str.replace("Z", "+00:00"))
                if start_dt.tzinfo is None:
                    start_dt = start_dt.replace(tzinfo=timezone.utc)

                if now <= start_dt <= cutoff:
                    results.append({
                        "title": e.get("summary", "Untitled"),
                        "time": start_dt.isoformat(),
                        "location": e.get("location", "")
                    })
            except (ValueError, TypeError):
                continue

        return results
    except Exception as exc:
        logger.debug("get_upcoming_events failed: %s", exc)
        return []


def _get_vault_store():
    """Best-effort: get the live store for vault indexing."""
    try:
        from main import get_app
        app = get_app()
        if app:
            return app.state.memory_manager._store
    except Exception:
        pass
    return None


async def _exec_save_vault_note(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        root = args.get("root", "personal")
        title = args["title"]
        content = args["content"]
        if not title.endswith(".md"):
            title += ".md"
        virtual_path = f"{root}/{title}"
        provider = VaultProvider(store=_get_vault_store())
        await provider.write_note(user_id, virtual_path, content)
        return f"Note '{args['title']}' saved to your {root} vault."
    except Exception as exc:
        logger.error("save_vault_note failed: %s", exc)
        return f"Failed to save note '{args.get('title')}': {exc}"


async def _exec_read_vault_note(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        root = args.get("root", "personal")
        title = args["title"]
        if not title.endswith(".md"):
            title += ".md"
        virtual_path = f"{root}/{title}"
        provider = VaultProvider()
        content = await provider.read_note(user_id, virtual_path)
        if len(content) > 3000:
            content = content[:3000] + "\n\n[... note truncated ...]"
        return content
    except FileNotFoundError:
        return f"No note named '{args['title']}' found in the {args.get('root', 'personal')} vault."
    except Exception as exc:
        logger.error("read_vault_note failed: %s", exc)
        return f"Failed to read note '{args.get('title')}': {exc}"


async def _exec_search_vault(args: dict, user_id: str) -> str:
    try:
        from providers.vault.vault_provider import VaultProvider
        provider = VaultProvider(store=_get_vault_store())
        results = await provider.search_text(user_id, args["query"])
        if not results:
            return f"No notes found matching '{args['query']}'."
        lines = [
            f"- {r.get('title', r['virtual_path'])} ({r['virtual_path']})" for r in results[:10]]
        return f"Found {len(results)} note(s):\n" + "\n".join(lines)
    except Exception as exc:
        logger.error("search_vault failed: %s", exc)
        return f"Vault search failed: {exc}"


async def _exec_code_interpreter(args: dict, user_id: str) -> str:
    try:
        from core.code_interpreter import run_code
        return await run_code(args["code"])
    except Exception as exc:
        logger.error("code_interpreter failed: %s", exc)
        return f"Failed to run code: {exc}"


async def _exec_mow_command(args: dict, user_id: str) -> str:
    try:
        from api.routes.vector_fleet import queue_command, get_fleet_state, get_first_unit_id

        command = args["command"]
        unit_id = args.get("unit_id") or get_first_unit_id()

        if not unit_id:
            return (
                "No mower units are registered yet. "
                "Make sure Voyager is running and has connected to River Song."
            )

        fleet = get_fleet_state()
        state = fleet.get(unit_id, {})
        last_seen = state.get("last_seen")
        import time
        online = last_seen and (time.time() - last_seen) < 30

        queued = queue_command(unit_id, command, {})
        if not queued:
            return f"Could not queue '{command}' — unit '{unit_id}' is unknown."

        label = {
            "mow_start": "start mowing",
            "mow_stop": "stop mowing",
            "return_home": "return to dock",
            "estop": "EMERGENCY STOP",
            "estop_reset": "reset the E-stop",
        }.get(command, command)

        if online:
            return f"Command queued: {label}. Voyager will execute it on the next poll (within 100 ms)."
        else:
            ago = f"{round(time.time() - last_seen)}s ago" if last_seen else "never"
            return (
                f"Command queued: {label}. "
                f"Note: Voyager was last seen {ago} and may be offline. "
                "It will pick up the command when it reconnects."
            )
    except Exception as exc:
        logger.error("mow_command failed: %s", exc)
        return f"Failed to send mower command: {exc}"

async def _exec_set_timer(args: dict, user_id: str) -> str:
    label = args.get("label", "Timer")
    duration = int(args.get("duration_seconds", 60))
    
    async def _timer_task():
        await asyncio.sleep(duration)
        from api.routes.culinary import _ws_manager
        from core.family import resolve_module_owner
        uid = resolve_module_owner(user_id, "culinary")
        # In culinary, household ID is usually needed for broadcast. Wait, _ws_manager broadcasts to household_id.
        # So we need to get household_id.
        from sqlalchemy.orm import Session
        from api.routes.culinary import get_db, _get_household
        
        # We need a new DB session inside the background task since the current one might be closed
        from database.core import engine
        from sqlalchemy.orm import sessionmaker
        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
        
        db = SessionLocal()
        try:
            hh = _get_household(db, uid)
            await _ws_manager.broadcast(hh.id, "timer_fired", {"label": label, "duration": duration})
        except Exception as e:
            logger.error(f"Error in timer task: {e}")
        finally:
            db.close()
            
    asyncio.create_task(_timer_task())
    return f"Timer '{label}' set for {duration} seconds."

async def _resolve_vehicle(query: str | None, user_id: str | None):
    from vehicles.management import get_vehicles
    from core.family import resolve_module_owner
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    if not user_id:
        user_id = "primary_user"
    owner_id = resolve_module_owner(user_id, "maintenance")
    try:
        vehicles = get_vehicles(db, owner_id)
        if not vehicles:
            return None
        # simple fuzzy match
        query = (query or "").lower()
        for v in vehicles:
            if v.nickname and query in v.nickname.lower(): return v.id
            if v.make and query in v.make.lower(): return v.id
            if v.model and query in v.model.lower(): return v.id
        # return first if only one
        if len(vehicles) == 1:
            return vehicles[0].id
        return None
    finally:
        db.close()

async def _exec_get_vehicle_status(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from api.routes.vehicles import get_maintenance_timeline
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        from core.family import resolve_module_owner
        owner_id = resolve_module_owner(user_id, "maintenance")
        tl = get_maintenance_timeline(str(vid), None, None, db, owner_id)
        return str(tl)
    except Exception as e:
        return f"Error: {e}"
    finally:
        db.close()

async def _exec_get_vehicle_spec(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from vehicles.models import VehicleCheckPoint
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        cps = db.query(VehicleCheckPoint).filter(VehicleCheckPoint.vehicle_id == str(vid)).all()
        q = args.get("item", "").lower()
        for cp in cps:
            if q in cp.description.lower():
                return f"Specs for {cp.description}: Torque {cp.torque_ft_lb} ft-lb / {cp.torque_nm} nm, Fluid {cp.fluid_volume} {cp.expected_spec}"
        return "Spec not found."
    finally:
        db.close()

async def _exec_query_vehicle_manual(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    from providers.rag.rag_provider import RAGProvider
    rag = RAGProvider()
    res = await rag.query_documents(args.get("question", ""), where={"vehicle_id": str(vid)}, n_results=3)
    return str(res)

async def _exec_record_odometer(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    val = args.get("value")
    from database.core import engine
    from sqlalchemy.orm import sessionmaker
    from vehicles.models import UsageReading, UsageSource
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    try:
        db.add(UsageReading(vehicle_id=str(vid), value=val, source=UsageSource.MANUAL))
        db.commit()
        return f"Recorded odometer {val} for vehicle."
    finally:
        db.close()

async def _exec_find_parts(args: dict, user_id: str) -> str:
    vid = args.get("vehicle_id") or await _resolve_vehicle(args.get("vehicle"), user_id)
    if not vid: return "Vehicle not found."
    # AI lookup verified pipeline
    from core.tools import _exec_web_search
    return await _exec_web_search({"query": f"{args.get('vehicle')} {args.get('job')} OEM part number alternatives price"}, user_id)


async def _exec_design_3d_model(args: dict, user_id: str) -> str:
    from providers.cad.cad_engine import get_cad_engine
    engine = get_cad_engine()
    name = args.get("name", "3d_part").strip()
    scad_code = args.get("scad_code", "")
    description = args.get("description", "")
    res = await engine.compile_scad(scad_code=scad_code, name=name, user_id=user_id)
    if res.error:
        return f"Error compiling 3D CAD model: {res.error}\n\nSCAD Code:\n```openscad\n{scad_code}\n```"
    
    lines = [
        f"✅ Successfully designed and compiled 3D CAD Model: **{name}**",
        f"- **Model ID**: `{res.model_id}`",
        f"- **Bounding Dimensions (X × Y × Z)**: {res.dimensions_mm[0]} mm × {res.dimensions_mm[1]} mm × {res.dimensions_mm[2]} mm",
        f"- **Volume**: {res.volume_cm3} cm³",
        f"- **Surface Area**: {res.surface_area_cm2} cm²",
        f"- **Estimated PLA Mass**: ~{res.estimated_mass_grams} grams",
        f"- **Estimated 3D Print Time**: ~{res.estimated_print_time_minutes} minutes",
        f"- **Mesh Watertightness**: {'Yes (Print Ready)' if res.is_watertight else 'No (Inspect Mesh)'}",
        f"\n```stl\n/api/cad/models/{res.model_id}/stl\n```\n",
        f"*(Interact with the 3D model above or download the STL file)*",
    ]
    return "\n".join(lines)


async def _exec_run_sandbox_code(args: dict, user_id: str) -> str:
    from core.sandbox import get_sandbox_runner
    runner = get_sandbox_runner()
    code = args.get("code", "")
    lang = args.get("language", "python")
    res = await runner.execute_code(code=code, language=lang, user_id=user_id)
    status_icon = "✅ Success" if res.success else "❌ Failed"
    out_lines = [
        f"{status_icon} (Exit code: {res.exit_code}, Duration: {res.duration_ms}ms)",
    ]
    if res.stdout:
        out_lines.append(f"**Output (stdout)**:\n```\n{res.stdout.strip()}\n```")
    if res.stderr:
        out_lines.append(f"**Errors/Traceback (stderr)**:\n```\n{res.stderr.strip()}\n```")
    if res.artifacts:
        out_lines.append(f"**Generated Artifacts**: {', '.join(res.artifacts)}")
    return "\n\n".join(out_lines)


async def _exec_render_diagram(args: dict, user_id: str) -> str:
    title = args.get("title", "Architecture Diagram")
    mermaid = args.get("mermaid_code", "").strip()
    return f"### 📊 {title}\n\n```mermaid\n{mermaid}\n```"


# Memory + note executors live in core/tools_memory.py (god-file #3);
# re-exported so execute_tool's dispatch and external callers are unchanged.
from core.tools_memory import (  # noqa: E402
    _exec_remember_fact,
    _exec_forget_memory,
    _exec_recall_memory,
    _exec_update_memory,
    _get_vault_provider,
    _exec_take_note,
    _exec_append_note,
    _exec_journal,
    _exec_find_notes,
    _exec_read_note,
)


# ---------------------------------------------------------------------------
# Media and announcements — phase H4 of docs/smart-home-plan.md.
#
# Home Assistant owns the speakers; these resolve a spoken room or player name
# through the same ha_entities sync the rest of the home code uses, so "play
# music in the kitchen" needs no second registry of its own.
# ---------------------------------------------------------------------------

async def _media_players_in(target: Optional[str]) -> list:
    """media_player entity ids matching a room or player name.

    An empty or "everywhere" target means every player in the house, which is
    what an announcement usually wants.
    """
    from main import get_app
    app = get_app()
    if not app:
        return []
    store = app.state.memory_manager._store
    try:
        rows = await store.execute_read_async(
            "SELECT entity_id, name, area FROM ha_entities "
            "WHERE domain = 'media_player' AND hidden = 0")
    except Exception as e:
        logger.error("Could not read media players: %s", e)
        return []

    if not target or target.strip().lower() in ("all", "everywhere", "house"):
        return [r["entity_id"] for r in rows]

    t = target.strip().lower()
    exact = [r["entity_id"] for r in rows
             if (r["area"] or "").lower() == t or (r["name"] or "").lower() == t]
    if exact:
        return exact
    # Fall back to a loose contains match so "kitchen speaker" finds the
    # kitchen, rather than failing on a word the user did not know mattered.
    return [r["entity_id"] for r in rows
            if t in (r["name"] or "").lower() or t in (r["area"] or "").lower()]


async def _exec_play_media(args: dict, user_id: str) -> str:
    from core.family import is_feature_enabled_for
    if not await is_feature_enabled_for(user_id, "home"):
        return "Home control isn't enabled for you."

    target = args.get("room") or args.get("player")
    query = (args.get("query") or "").strip()
    players = await _media_players_in(target)
    if not players:
        where = f" in the {target}" if target else ""
        return f"I couldn't find a speaker{where}."

    from providers.smart_home.home_assistant import build_ha_client
    try:
        async with build_ha_client() as client:
            for eid in players:
                if query:
                    # search_media is what HA exposes for "play this by name";
                    # without a query this is a plain resume.
                    await client.call_service(
                        "media_player", "play_media", entity_id=eid,
                        media_content_id=query, media_content_type="music")
                else:
                    await client.call_service(
                        "media_player", "media_play", entity_id=eid)
    except Exception:
        return ("Home Assistant isn't reachable right now — I couldn't start "
                "playback.")

    where = f" in the {target}" if target else ""
    what = f" '{query}'" if query else ""
    return f"Playing{what}{where}."


async def _exec_media_control(args: dict, user_id: str) -> str:
    from core.family import is_feature_enabled_for
    if not await is_feature_enabled_for(user_id, "home"):
        return "Home control isn't enabled for you."

    action = (args.get("action") or "").lower()
    target = args.get("room") or args.get("player")
    players = await _media_players_in(target)
    if not players:
        return f"I couldn't find a speaker{f' in the {target}' if target else ''}."

    service_for = {"pause": "media_pause", "stop": "media_stop",
                   "resume": "media_play", "play": "media_play",
                   "next": "media_next_track", "previous": "media_previous_track"}
    from providers.smart_home.home_assistant import build_ha_client
    try:
        async with build_ha_client() as client:
            if action == "volume":
                level = args.get("level")
                if level is None:
                    return "Tell me what volume to set, from 0 to 100."
                level = max(0.0, min(1.0, float(level) / 100.0))
                for eid in players:
                    await client.call_service("media_player", "volume_set",
                                              entity_id=eid, volume_level=level)
                return f"Volume set to {int(level * 100)}%."
            service = service_for.get(action)
            if not service:
                return f"I don't know how to '{action}' a speaker."
            for eid in players:
                await client.call_service("media_player", service, entity_id=eid)
    except Exception:
        return "Home Assistant isn't reachable right now."
    return f"Done — {action}."


async def _exec_announce(args: dict, user_id: str) -> str:
    """Speak a message through the house speakers.

    Uses Home Assistant's own tts service rather than River's TTS pool: the
    audio has to reach a speaker HA owns, and handing HA the text is one hop
    instead of rendering a clip here and serving it back over the network.
    """
    from core.family import is_feature_enabled_for
    if not await is_feature_enabled_for(user_id, "home"):
        return "Home control isn't enabled for you."

    message = (args.get("message") or "").strip()
    if not message:
        return "Tell me what to announce."
    target = args.get("room")
    players = await _media_players_in(target)
    if not players:
        where = f" in the {target}" if target else ""
        return f"I couldn't find a speaker{where} to announce on."

    from providers.smart_home.home_assistant import build_ha_client
    try:
        async with build_ha_client() as client:
            for eid in players:
                await client.call_service(
                    "tts", "speak", entity_id=eid, message=message)
    except Exception:
        return ("Home Assistant isn't reachable right now — the announcement "
                "didn't play.")

    where = f" in the {target}" if target else " everywhere"
    return f"Announced{where}."
